# Proyecto: Precios de Laptos

In [1]:
# Módulo PANDAS
import pandas as pd

In [2]:
# Jalar el data frame
datos=pd.read_csv("laptopPrice.csv")
# Ojo con las diagonales cuando tengan que definir otra ruta..
# pd.read_csv("C:/Users/migue/Documents/Diplomado_ciencia_datos/datos/nombre_archivo.csv")

In [3]:
datos

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [4]:
# Para ver que si se cargo el dataframe
datos.head()  # Las primeras cinco lineas del dataframe

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0

In [5]:
# Los últimos 5
datos.tail()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

In [6]:
# datos.head(n)  : les muestra las primera n filas del dataframe datos
datos.head(10)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240

In [7]:
# datos.tail(n)  : les muestra las ultimas n filas del dataframe datos
datos.tail(10)

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
813,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,162990,3 stars,0,0
814,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,130500,3 stars,0,0
815,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,116990,3 stars,0,0
816,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,138990,3 stars,0,0
817,ASUS,AMD,Ryzen 9,Not Available,4 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,Yes,Yes,234990,3 stars,0,0
818,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,135990,3 stars,0,0
819,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,144990,3 stars,0,0
820,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,149990,3 stars,0,0
821,ASUS,AMD,Ryzen 9,Not Available,4 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,142990,3 stars,0,0
822,Lenovo,AMD,Ryzen 5,10th,8 GB,DDR4,512 GB,0 GB,DOS,64-bit,0 GB,ThinNlight,No warranty,No,No,57490,4 stars,18,4

# Ayuda con los métodos de los módulos.
1. Para hallar los métodos que están definidos en cada uno de los modulos de Python, se puede hacer los siguiente:

nombre_del_modulo.  acontinuación presionamos tecla de tabular
(o el alias)

2. Para revisar los parámetros de un método en python procedemos como sigue:

nombre_del_modulo.nombre_del_método( acontinuación presionamos las teclas shift+ tab
(o el alias)

In [13]:
# Ejemplos:
#pd.concat()

# Siempre hay que importar el módulo primero... antes de solicitar la ayuda
import os
#os.chdir()

In [14]:
# Cómo mostramos TODAS las entradas del DataFrame 
pd.set_option("display.max_rows",1000)  # Le cambio el parámetro para que me despliegue hasta 1000 renglones
datos

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240
10,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,93700,4 stars,259,47
11,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,72990,4 stars,425,67
12,Avita,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,17490,3 stars,1120,196
13,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,35990,3 stars,0,0
15,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,56490,3 stars,0,0
16,HP,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,65390,3 stars,0,0
17,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31999,4 stars,286,19
18,HP,Intel,Celeron Dual,Not Available,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,32490,4 stars,58,6
19,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31799,3 stars,0,0
20,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,29890,4 stars,7,0
21,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,23990,3 stars,15279,1947
22,HP,Intel,Core i3,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32955,4 stars,311,27
23,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,46200,4 stars,47,7
24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,34429,4 stars,37,6
25,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,2 years,No,Yes,37990,4 stars,2080,235
26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,35990,4 stars,1479,181
27,ASUS,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33980,4 stars,67,3
28,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,273,30
29,DELL,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39490,4 stars,1267,171
30,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,53990,4 stars,14,0
31,acer,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,3 stars,0,0
32,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,37990,4 stars,284,39
33,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,37890,4 stars,44,5
34,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,4 stars,33,4
35,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,37990,4 stars,286,36
36,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,10,5
37,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
38,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,4 stars,543,65
39,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42490,4 stars,9,1
40,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,36990,4 stars,1178,137
41,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,53990,4 stars,299,41
42,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36990,4 stars,20,1
43,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,No,38940,4 stars,758,64
44,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,39490,4 stars,634,64
45,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
46,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,Yes,39999,5 stars,4,0
47,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,42990,4 stars,17,2
48,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,49990,4 stars,24,5
49,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41490,4 stars,1753,165
50,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,41990,4 stars,216,21
51,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,4 stars,1084,160
52,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38490,3 stars,19,3
53,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,106,13
54,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,42,4
55,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36490,3 stars,0,0
56,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38970,3 stars,0,0
57,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44900,4 stars,1029,107
58,MSI,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,38990,4 stars,53,11
59,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,44427,3 stars,0,0
60,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,0,0
61,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,40200,3 stars,48,1
62,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40990,3 stars,3,0
63,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,42490,3 stars,0,0
64,acer,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23990,3 stars,61,4
65,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,Yes,No,71999,4 stars,97,13
66,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,39990,4 stars,181,19
67,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,41998,4 stars,529,39
68,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,0,0
69,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,Yes,39999,3 stars,0,0
70,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,39990,3 stars,0,0
71,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39998,4 stars,10,1
72,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42490,4 stars,5205,561
73,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,3,0
74,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,48490,3 stars,0,0
75,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44376,4 stars,1090,96
76,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43900,3 stars,0,0
77,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,46690,3 stars,0,0
78,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40990,5 stars,1,1
79,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,4 stars,44,2
80,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,43990,3 stars,0,0
81,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,4 stars,70,9
82,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48500,3 stars,0,0
83,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,48990,3 stars,0,0
84,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23490,4 stars,632,92
85,HP,Intel,Core i3,8th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,54238,4 stars,71,8
86,ASUS,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,37990,4 stars,990,108
87,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,158,18
88,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,681,59
89,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,4 stars,130,12
90,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,30,4
91,ASUS,Intel,Core i3,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,Yes,Yes,51990,4 stars,6,2
92,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48990,4 stars,174,30
93,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,40,7
94,Lenovo,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,3 stars,13,1
95,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,45990,4 stars,184,29
96,HP,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42490,4 stars,1296,126
97,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43970,4 stars,571,56
98,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,2551,297
99,MSI,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,48990,4 stars,17,3
100,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,54990,4 stars,35,3
101,MSI,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,40990,4 stars,118,17
102,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,0,0
103,Lenovo,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,Yes,No,54990,4 stars,245,34
104,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,2058,305
105,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41250,4 stars,117,11
106,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,44990,3 stars,0,0
107,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,74,11
108,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,60790,4 stars,10,1
109,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,45650,4 stars,39,4
110,DELL,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,29,7
111,DELL,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,45490,4 stars,43,4
112,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44990,3 stars,0,0
113,Lenovo,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,2 years,No,Yes,42990,4 stars,984,99
114,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,45490,4 stars,523,66
115,HP,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38799,4 stars,30,1
116,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,69267,3 stars,0,0
117,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,51649,3 stars,0,0
118,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,47990,4 stars,1605,215
119,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
120,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,1869,234
121,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,44890,3 stars,7,0
122,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41490,4 stars,4008,519
123,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,1 year,No,No,50990,3 stars,0,0
124,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,48900,4 stars,1278,135
125,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
126,DELL,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,41790,3 stars,0,0
127,Lenovo,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,57999,3 stars,10,2
128,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,45930,3 stars,0,0
129,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,55490,4 stars,143,15
130,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,32890,3 stars,28,4
131,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,35990,4 stars,2124,233
132,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42490,4 stars,276,40
133,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42190,3 stars,250,21
134,DELL,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39490,4 stars,1917,189
135,HP,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43690,4 stars,4999,490
136,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,17,0
137,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43800,4 stars,17,0
138,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38990,3 stars,0,0
139,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,34990,3 stars,4203,490
140,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38900,3 stars,13,0
141,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,3 stars,15,1
142,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40890,4 stars,527,46
143,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,3 stars,103,10
144,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,3 stars,324,45
145,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,4 stars,69,5
146,DELL,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43970,3 stars,16,0
147,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39790,3 stars,40,3
148,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,35590,3 stars,12,1
149,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,36490,3 stars,1146,175
150,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,1850,216
151,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,43,7
152,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,43400,4 stars,231,26
153,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,24990,4 stars,502,93
154,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,40750,4 stars,1096,116
155,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43000,4 stars,313,35
156,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38000,4 stars,7,0
157,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,37990,3 stars,265,46
158,HP,Intel,Core i3,7th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,2 GB,Casual,No warranty,No,No,49279,4 stars,38,3
159,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,7,2
160,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41500,3 stars,4,0
161,acer,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,36999,3 stars,0,0
162,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,42900,3 stars,0,0
163,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21490,3 stars,818,113
164,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41480,3 stars,25,4
165,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32990,2 stars,12,0
166,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38680,3 stars,17,1
167,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23990,4 stars,974,170
168,DELL,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,40390,3 stars,83,15
169,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,31,6
170,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,20490,3 stars,637,91
171,DELL,Intel,Core i3,10th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41490,5 stars,7,5

# Atributos del DataFrame

In [15]:
# Dimensiones del dataframe: atributo 
datos.shape

(823, 19)

Tenemos 823 laptops y en cada una de ellas hemos medido 19 atributos

In [16]:
# Los atributos son: Las variables que estamos midiendo
# con el atributo columns
datos.columns

Index(['brand', 'processor_brand', 'processor_name', 'processor_gnrtn',
       'ram_gb', 'ram_type', 'ssd', 'hdd', 'os', 'os_bit', 'graphic_card_gb',
       'weight', 'warranty', 'Touchscreen', 'msoffice', 'Price', 'rating',
       'Number of Ratings', 'Number of Reviews'],
      dtype='object')

In [17]:
datos.dtypes

brand                object
processor_brand      object
processor_name       object
processor_gnrtn      object
ram_gb               object
ram_type             object
ssd                  object
hdd                  object
os                   object
os_bit               object
graphic_card_gb      object
weight               object
warranty             object
Touchscreen          object
msoffice             object
Price                 int64
rating               object
Number of Ratings     int64
Number of Reviews     int64
dtype: object

In [18]:
# Método más general para obtener la información del dataframe
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 823 entries, 0 to 822
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              823 non-null    object
 1   processor_brand    823 non-null    object
 2   processor_name     823 non-null    object
 3   processor_gnrtn    823 non-null    object
 4   ram_gb             823 non-null    object
 5   ram_type           823 non-null    object
 6   ssd                823 non-null    object
 7   hdd                823 non-null    object
 8   os                 823 non-null    object
 9   os_bit             823 non-null    object
 10  graphic_card_gb    823 non-null    object
 11  weight             823 non-null    object
 12  warranty           823 non-null    object
 13  Touchscreen        823 non-null    object
 14  msoffice           823 non-null    object
 15  Price              823 non-null    int64
 16  rating             823 non-null    object
 17  Number of Ratings  823 non-null    int64
 18  Number of Reviews  823 non-null    int64
dtypes: int64(3), object(16)
memory usage: 122.3+ KB

In [19]:
datos.describe()

               Price  Number of Ratings  Number of Reviews
count     823.000000         823.000000         823.000000
mean    76745.177400         315.301337          37.609964
std     45101.790525        1047.382654         121.728017
min     16990.000000           0.000000           0.000000
25%     46095.000000           0.000000           0.000000
50%     64990.000000          17.000000           2.000000
75%     89636.000000         139.500000          18.000000
max    441990.000000       15279.000000        1947.000000

# Funciones sobre DataFrame

In [20]:
len(datos)  # Regresa el número de renglones en el dataframe

823

In [21]:
round(datos,2)  # Redondeo a 2 cifras decimales, cuando aplica para variables numéricas

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
8,Lenovo,Intel,Core i5,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,49999,3 stars,0,0
9,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,59990,4 stars,1946,240
10,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,93700,4 stars,259,47
11,acer,AMD,Ryzen 5,10th,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,4 GB,Casual,No warranty,No,No,72990,4 stars,425,67
12,Avita,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,17490,3 stars,1120,196
13,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,35990,3 stars,0,0
15,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,56490,3 stars,0,0
16,HP,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,65390,3 stars,0,0
17,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31999,4 stars,286,19
18,HP,Intel,Celeron Dual,Not Available,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,32490,4 stars,58,6
19,Lenovo,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,31799,3 stars,0,0
20,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,29890,4 stars,7,0
21,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,23990,3 stars,15279,1947
22,HP,Intel,Core i3,7th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32955,4 stars,311,27
23,HP,Intel,Core i5,7th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,46200,4 stars,47,7
24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,34429,4 stars,37,6
25,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,2 years,No,Yes,37990,4 stars,2080,235
26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,35990,4 stars,1479,181
27,ASUS,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33980,4 stars,67,3
28,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,273,30
29,DELL,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39490,4 stars,1267,171
30,HP,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,53990,4 stars,14,0
31,acer,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,3 stars,0,0
32,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,37990,4 stars,284,39
33,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,37890,4 stars,44,5
34,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,4 stars,33,4
35,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,37990,4 stars,286,36
36,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,10,5
37,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
38,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,4 stars,543,65
39,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42490,4 stars,9,1
40,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,36990,4 stars,1178,137
41,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,53990,4 stars,299,41
42,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36990,4 stars,20,1
43,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,No,38940,4 stars,758,64
44,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,39490,4 stars,634,64
45,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
46,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,Yes,39999,5 stars,4,0
47,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,42990,4 stars,17,2
48,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,49990,4 stars,24,5
49,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41490,4 stars,1753,165
50,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,41990,4 stars,216,21
51,Lenovo,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,4 stars,1084,160
52,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38490,3 stars,19,3
53,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,106,13
54,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,42,4
55,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36490,3 stars,0,0
56,Lenovo,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38970,3 stars,0,0
57,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44900,4 stars,1029,107
58,MSI,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,38990,4 stars,53,11
59,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,44427,3 stars,0,0
60,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,0,0
61,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,40200,3 stars,48,1
62,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40990,3 stars,3,0
63,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,42490,3 stars,0,0
64,acer,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23990,3 stars,61,4
65,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,Yes,No,71999,4 stars,97,13
66,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,39990,4 stars,181,19
67,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,41998,4 stars,529,39
68,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,0,0
69,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,2 years,No,Yes,39999,3 stars,0,0
70,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,39990,3 stars,0,0
71,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39998,4 stars,10,1
72,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42490,4 stars,5205,561
73,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,3,0
74,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,48490,3 stars,0,0
75,HP,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44376,4 stars,1090,96
76,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43900,3 stars,0,0
77,DELL,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,46690,3 stars,0,0
78,Lenovo,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40990,5 stars,1,1
79,DELL,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,4 stars,44,2
80,Lenovo,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,43990,3 stars,0,0
81,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,4 stars,70,9
82,DELL,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48500,3 stars,0,0
83,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,48990,3 stars,0,0
84,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23490,4 stars,632,92
85,HP,Intel,Core i3,8th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,54238,4 stars,71,8
86,ASUS,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,37990,4 stars,990,108
87,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,158,18
88,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,681,59
89,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,4 stars,130,12
90,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,30,4
91,ASUS,Intel,Core i3,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,Yes,Yes,51990,4 stars,6,2
92,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48990,4 stars,174,30
93,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,40,7
94,Lenovo,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,38990,3 stars,13,1
95,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,45990,4 stars,184,29
96,HP,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42490,4 stars,1296,126
97,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43970,4 stars,571,56
98,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,2551,297
99,MSI,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,48990,4 stars,17,3
100,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,54990,4 stars,35,3
101,MSI,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,40990,4 stars,118,17
102,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,0,0
103,Lenovo,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,Yes,No,54990,4 stars,245,34
104,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,2058,305
105,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41250,4 stars,117,11
106,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,44990,3 stars,0,0
107,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,74,11
108,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,60790,4 stars,10,1
109,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,45650,4 stars,39,4
110,DELL,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,29,7
111,DELL,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,45490,4 stars,43,4
112,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44990,3 stars,0,0
113,Lenovo,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,2 years,No,Yes,42990,4 stars,984,99
114,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,45490,4 stars,523,66
115,HP,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38799,4 stars,30,1
116,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,69267,3 stars,0,0
117,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,51649,3 stars,0,0
118,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,47990,4 stars,1605,215
119,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
120,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,1869,234
121,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,44890,3 stars,7,0
122,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41490,4 stars,4008,519
123,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,32-bit,0 GB,ThinNlight,1 year,No,No,50990,3 stars,0,0
124,HP,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,48900,4 stars,1278,135
125,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
126,DELL,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,41790,3 stars,0,0
127,Lenovo,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,57999,3 stars,10,2
128,DELL,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,45930,3 stars,0,0
129,HP,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,55490,4 stars,143,15
130,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,32890,3 stars,28,4
131,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,35990,4 stars,2124,233
132,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42490,4 stars,276,40
133,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,42190,3 stars,250,21
134,DELL,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39490,4 stars,1917,189
135,HP,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43690,4 stars,4999,490
136,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,17,0
137,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43800,4 stars,17,0
138,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38990,3 stars,0,0
139,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,34990,3 stars,4203,490
140,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38900,3 stars,13,0
141,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39990,3 stars,15,1
142,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,40890,4 stars,527,46
143,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,3 stars,103,10
144,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,3 stars,324,45
145,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,4 stars,69,5
146,DELL,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,43970,3 stars,16,0
147,HP,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,39790,3 stars,40,3
148,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,35590,3 stars,12,1
149,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,36490,3 stars,1146,175
150,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,1850,216
151,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,43,7
152,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,43400,4 stars,231,26
153,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,24990,4 stars,502,93
154,HP,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,40750,4 stars,1096,116
155,DELL,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,43000,4 stars,313,35
156,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38000,4 stars,7,0
157,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,37990,3 stars,265,46
158,HP,Intel,Core i3,7th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,2 GB,Casual,No warranty,No,No,49279,4 stars,38,3
159,Lenovo,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,7,2
160,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41500,3 stars,4,0
161,acer,Intel,Core i3,11th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,36999,3 stars,0,0
162,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,42900,3 stars,0,0
163,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21490,3 stars,818,113
164,DELL,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41480,3 stars,25,4
165,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32990,2 stars,12,0
166,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38680,3 stars,17,1
167,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23990,4 stars,974,170
168,DELL,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,40390,3 stars,83,15
169,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,31,6
170,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,20490,3 stars,637,91
171,DELL,Intel,Core i3,10th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41490,5 stars,7,5

In [23]:
# Qué marcas de Laptop están en tu dataframe?

# Seleccionar una serie/columna de un dataframe
# sintaxis: nombre_dataframe["nombre_serie"]
datos["brand"] # Seleccionamos solo la marca de la laptop
datos["brand"].unique()   # Devuelve los valores únicos de la marca

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [24]:
# ¿Cuántas computadoras de cada marca están en tu estudio?
datos["brand"].value_counts()   # Devuelve el número de laptops de cada marca

ASUS      249
DELL      151
Lenovo    144
HP        136
acer       51
MSI        50
APPLE      28
Avita      14
Name: brand, dtype: int64

In [25]:
# En porcentajes?
datos["brand"].value_counts(normalize=True)   # Devuelve el porcentaje de laptops de cada marca

ASUS      0.302552
DELL      0.183475
Lenovo    0.174970
HP        0.165249
acer      0.061968
MSI       0.060753
APPLE     0.034022
Avita     0.017011
Name: brand, dtype: float64

In [ ]:
# El 30.25% de las laptops que más se venden son de la marca ASUS.

In [29]:
# Seleccionar una numérica, por ejemplo precio..
datos["Price"]

0       34649
1       38999
2       39999
3       69990
4       26990
5       22990
6       21990
7       58799
8       49999
9       59990
10      93700
11      72990
12      17490
13      22990
14      35990
15      56490
16      65390
17      31999
18      32490
19      31799
20      29890
21      23990
22      32955
23      46200
24      34429
25      37990
26      35990
27      33980
28      39990
29      39490
30      53990
31      38990
32      37990
33      37890
34      38990
35      37990
36      41990
37      45990
38      39990
39      42490
40      36990
41      53990
42      36990
43      38940
44      39490
45      45990
46      39999
47      42990
48      49990
49      41490
50      41990
51      41990
52      38490
53      38990
54      44990
55      36490
56      38970
57      44900
58      38990
59      44427
60      35990
61      40200
62      40990
63      42490
64      23990
65      71999
66      39990
67      41998
68      41990
69      39999
70      39990
71      39998
72      42490
73      41990
74      48490
75      44376
76      43900
77      46690
78      40990
79      39990
80      43990
81      36990
82      48500
83      48990
84      23490
85      54238
86      37990
87      42990
88      42990
89      35990
90      42990
91      51990
92      48990
93      42990
94      38990
95      45990
96      42490
97      43970
98      39990
99      48990
100     54990
101     40990
102     41990
103     54990
104     44990
105     41250
106     44990
107     42990
108     60790
109     45650
110     41990
111     45490
112     44990
113     42990
114     45490
115     38799
116     69267
117     51649
118     47990
119     40990
120     42990
121     44890
122     41490
123     50990
124     48900
125     40990
126     41790
127     57999
128     45930
129     55490
130     32890
131     35990
132     42490
133     42190
134     39490
135     43690
136     35990
137     43800
138     38990
139     34990
140     38900
141     39990
142     40890
143     36990
144     39990
145     41990
146     43970
147     39790
148     35590
149     36490
150     38990
151     33990
152     43400
153     24990
154     40750
155     43000
156     38000
157     37990
158     49279
159     38999
160     41500
161     36999
162     42900
163     21490
164     41480
165     32990
166     38680
167     23990
168     40390
169     33990
170     20490
171     41490
172     45490
173     44490
174     41890
175     42990
176     40990
177     48990
178     43590
179     44690
180     40990
181     43990
182     43590
183     41390
184     44290
185     48999
186     39990
187     46390
188     18990
189     17990
190     26470
191     27990
192     29999
193     25990
194     16990
195     24990
196     50990
197    119990
198     94190
199    106167
200     68090
201    139990
202     55990
203    102551
204     46990
205     76012
206     49490
207     86867
208     48990
209     55990
210     81998
211    136590
212     59490
213     49800
214     61999
215     54990
216     53990
217     52990
218     67990
219     57990
220     62300
221     52990
222     51990
223     61990
224     63990
225     65990
226     52990
227     49990
228     71990
229     47990
230     48490
231     72990
232     76990
233     89990
234     59990
235     65990
236     71990
237     71890
238     64990
239     65990
240     55999
241     73490
242     74490
243     58340
244     55999
245     67990
246     59990
247     82990
248     64190
249     70090
250     49990
251     55490
252     97990
253     54990
254     59990
255     53990
256     66999
257     60990
258     47990
259     59999
260     79990
261     63990
262     63990
263     59990
264     55990
265     59990
266     63990
267     69490
268     89390
269     74990
270     64990
271     66490
272     89702
273     70990
274     58990
275     57500
276     79990
277     56541
278     59990
279     64990
280     61290
281     54990
282     59990
283     84990
284     72500
285     59990
286     87990
287     57990
288     69490
289     68990
290     77990
291    105990
292     79990
293     55490
294     69990
295     84990
296     59990
297    111890
298     65990
299     72990
300     71090
301     74990
302     79990
303     55490
304     66490
305     53400
306     74500
307    114990
308     61990
309    159990
310    172090
311     74990
312     56490
313    147000
314     55990
315     77990
316    106490
317     70990
318     64990
319     57990
320     64990
321     54990
322    111999
323     70798
324     59990
325     99500
326     55990
327     72990
328     64990
329     57990
330     76990
331     62998
332     77990
333    114990
334     65990
335     88990
336    113590
337     73990
338     61000
339     99990
340     67990
341     70799
342     65990
343     53690
344     55990
345     53190
346     58999
347     71990
348     82000
349     84990
350     89998
351     99990
352     84990
353     69899
354     79990
355     76300
356     55999
357     72900
358     73990
359     84990
360     73519
361    126000
362     88990
363    114999
364     82990
365    109999
366     82990
367     79990
368    114990
369    129999
370    149990
371     71290
372     79500
373     82990
374     70980
375     99990
376     94000
377     82990
378     79990
379     85990
380     86990
381    105990
382     84990
383     59999
384     91999
385     78900
386    132790
387     60990
388     65556
389     70190
390     79590
391     65556
392     76990
393     65556
394     44990
395     84990
396     86999
397     78000
398     73063
399     73063
400    100990
401     74990
402     75990
403     84086
404     75990
405     77990
406     77990
407    179990
408    179990
409     82990
410     87990
411     84500
412     74190
413     64990
414    155411
415    125394
416     49990
417     46990
418     48990
419     59999
420     46990
421     52990
422     57999
423     52490
424     56990
425     61990
426     58090
427     56990
428     61597
429     81990
430     61249
431     58990
432     83990
433    291190
434    145990
435    179990
436     64990
437     46790
438     44599
439     72964
440     48790
441     56491
442     50990
443     55990
444     57990
445     52990
446     57990
447     56990
448     55490
449     62490
450     64990
451     59990
452     60190
453     54490
454     60990
455     55790
456     64990
457     58990
458     54990
459     71990
460     69900
461     65990
462     49990
463     58990
464     74590
465     58990
466     64990
467     66490
468     77900
469     67490
470     61990
471     58990
472     74999
473     68900
474     71695
475     62490
476     62317
477    207290
478     87990
479     73990
480     73990
481     73990
482     73990
483     73990
484     73990
485     57990
486     61990
487     79990
488     68990
489     85990
490     99990
491     77990
492     79990
493     93190
494     94990
495     84990
496     57990
497    102990
498     99990
499     94990
500    104000
501     76990
502     90190
503     88488
504    109990
505     86990
506     89990
507    239759
508     78990
509    121890
510     85990
511     94990
512     92000
513    162990
514    135300
515     64990
516    174527
517    162299
518    109190
519     99999
520    104990
521    109990
522     99990
523    244801
524     94990
525     86000
526    162399
527    119599
528    211753
529    110999
530     99990
531     81990
532     66990
533     84990
534    104990
535    134990
536     98990
537    144690
538     99990
539    119990
540    194990
541    124990
542    122410
543    179990
544    154990
545    122990
546    224990
547    279990
548    121990
549    116990
550    151098
551    129990
552    149999
553    139990
554    129990
555    171990
556     93955
557    234990
558    128500
559    102990
560    119990
561    120980
562    157249
563    229900
564    131500
565    154990
566    165990
567    119990
568    167990
569    165000
570     62990
571     85990
572     94990
573    136990
574    234990
575    159990
576    233990
577     93990
578    116941
579     63990
580     66990
581     82500
582    119990
583    159990
584     98912
585     92990
586    119990
587    169990
588    139990
589    192990
590    299990
591    269990
592    139990
593    265998
594    441990
595     86990
596    109990
597    109590
598    146490
599     85990
600    112990
601    104990
602    112990
603    132990
604    104990
605     85990
606    149990
607    125990
608    103990
609    101990
610    104990
611    131990
612    128990
613    184990
614    225990
615    124990
616    104990
617    149990
618    169990
619    225990
620    243990
621    309990
622    225990
623     45990
624     58100
625     62990
626     32990
627     33990
628     30990
629     36000
630     32990
631     35990
632     27990
633     25990
634     25990
635     30780
636     37990
637     35990
638     39490
639     36990
640     39990
641     33690
642     40590
643     37990
644     34500
645     36990
646     43490
647     41490
648     34990
649     44490
650     40590
651     42090
652     35990
653     39490
654     37390
655     52632
656     39990
657     43990
658     32917
659     34990
660     39990
661     41999
662     41990
663     44490
664     41990
665     44490
666     49990
667     44390
668     57990
669     56990
670     48990
671     49970
672     47990
673     48990
674     53990
675     52990
676     43990
677     59490
678     64990
679     47490
680     59990
681     69990
682     58990
683     59490
684     67500
685     48990
686     62450
687     58990
688     57999
689     56990
690     72990
691     65990
692     98020
693     63990
694     49890
695     49990
696     59490
697     73999
698     60990
699     76190
700     74798
701     58990
702     68100
703     77990
704     55090
705     91990
706     84208
707     44990
708     53490
709     76498
710     98920
711     54990
712     49990
713     52380
714     49990
715     52500
716     49990
717     75999
718     80990
719     59900
720     54590
721     75500
722     51890
723     78000
724     59999
725     64990
726     57900
727     81978
728     59990
729     49490
730     54990
731     68500
732     54990
733     54990
734     63990
735     80000
736     51990
737     62990
738     52990
739     75100
740     76990
741     79990
742     71990
743     71990
744     99990
745     79990
746     93990
747     82990
748    106990
749     92990
750     81490
751     56990
752     64990
753     60990
754     84988
755     90990
756     63990
757     63990
758     57999
759     72400
760     78990
761     59990
762    111990
763    109000
764     89990
765     78988
766     73138
767    106990
768     79990
769     89570
770     68500
771     73400
772     79990
773     84990
774     99990
775     72990
776     92990
777     84190
778    112990
779    114990
780     99990
781     95990
782    159990
783     76990
784    130990
785     99990
786    112990
787     77988
788     76000
789     99990
790    111000
791     84970
792     75990
793     89990
794     81990
795     80490
796    135990
797    154990
798    199990
799    114990
800    129990
801    114990
802    146990
803    104990
804    114990
805    124990
806    134990
807    141990
808    129990
809    142990
810    121990
811    124990
812    141990
813    162990
814    130500
815    116990
816    138990
817    234990
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, dtype: int64

In [32]:
# Otra manera de seleccionar una variable es con el punto.
# nombre_dataframe.nombre_serie
datos.Price

0       34649
1       38999
2       39999
3       69990
4       26990
5       22990
6       21990
7       58799
8       49999
9       59990
10      93700
11      72990
12      17490
13      22990
14      35990
15      56490
16      65390
17      31999
18      32490
19      31799
20      29890
21      23990
22      32955
23      46200
24      34429
25      37990
26      35990
27      33980
28      39990
29      39490
30      53990
31      38990
32      37990
33      37890
34      38990
35      37990
36      41990
37      45990
38      39990
39      42490
40      36990
41      53990
42      36990
43      38940
44      39490
45      45990
46      39999
47      42990
48      49990
49      41490
50      41990
51      41990
52      38490
53      38990
54      44990
55      36490
56      38970
57      44900
58      38990
59      44427
60      35990
61      40200
62      40990
63      42490
64      23990
65      71999
66      39990
67      41998
68      41990
69      39999
70      39990
71      39998
72      42490
73      41990
74      48490
75      44376
76      43900
77      46690
78      40990
79      39990
80      43990
81      36990
82      48500
83      48990
84      23490
85      54238
86      37990
87      42990
88      42990
89      35990
90      42990
91      51990
92      48990
93      42990
94      38990
95      45990
96      42490
97      43970
98      39990
99      48990
100     54990
101     40990
102     41990
103     54990
104     44990
105     41250
106     44990
107     42990
108     60790
109     45650
110     41990
111     45490
112     44990
113     42990
114     45490
115     38799
116     69267
117     51649
118     47990
119     40990
120     42990
121     44890
122     41490
123     50990
124     48900
125     40990
126     41790
127     57999
128     45930
129     55490
130     32890
131     35990
132     42490
133     42190
134     39490
135     43690
136     35990
137     43800
138     38990
139     34990
140     38900
141     39990
142     40890
143     36990
144     39990
145     41990
146     43970
147     39790
148     35590
149     36490
150     38990
151     33990
152     43400
153     24990
154     40750
155     43000
156     38000
157     37990
158     49279
159     38999
160     41500
161     36999
162     42900
163     21490
164     41480
165     32990
166     38680
167     23990
168     40390
169     33990
170     20490
171     41490
172     45490
173     44490
174     41890
175     42990
176     40990
177     48990
178     43590
179     44690
180     40990
181     43990
182     43590
183     41390
184     44290
185     48999
186     39990
187     46390
188     18990
189     17990
190     26470
191     27990
192     29999
193     25990
194     16990
195     24990
196     50990
197    119990
198     94190
199    106167
200     68090
201    139990
202     55990
203    102551
204     46990
205     76012
206     49490
207     86867
208     48990
209     55990
210     81998
211    136590
212     59490
213     49800
214     61999
215     54990
216     53990
217     52990
218     67990
219     57990
220     62300
221     52990
222     51990
223     61990
224     63990
225     65990
226     52990
227     49990
228     71990
229     47990
230     48490
231     72990
232     76990
233     89990
234     59990
235     65990
236     71990
237     71890
238     64990
239     65990
240     55999
241     73490
242     74490
243     58340
244     55999
245     67990
246     59990
247     82990
248     64190
249     70090
250     49990
251     55490
252     97990
253     54990
254     59990
255     53990
256     66999
257     60990
258     47990
259     59999
260     79990
261     63990
262     63990
263     59990
264     55990
265     59990
266     63990
267     69490
268     89390
269     74990
270     64990
271     66490
272     89702
273     70990
274     58990
275     57500
276     79990
277     56541
278     59990
279     64990
280     61290
281     54990
282     59990
283     84990
284     72500
285     59990
286     87990
287     57990
288     69490
289     68990
290     77990
291    105990
292     79990
293     55490
294     69990
295     84990
296     59990
297    111890
298     65990
299     72990
300     71090
301     74990
302     79990
303     55490
304     66490
305     53400
306     74500
307    114990
308     61990
309    159990
310    172090
311     74990
312     56490
313    147000
314     55990
315     77990
316    106490
317     70990
318     64990
319     57990
320     64990
321     54990
322    111999
323     70798
324     59990
325     99500
326     55990
327     72990
328     64990
329     57990
330     76990
331     62998
332     77990
333    114990
334     65990
335     88990
336    113590
337     73990
338     61000
339     99990
340     67990
341     70799
342     65990
343     53690
344     55990
345     53190
346     58999
347     71990
348     82000
349     84990
350     89998
351     99990
352     84990
353     69899
354     79990
355     76300
356     55999
357     72900
358     73990
359     84990
360     73519
361    126000
362     88990
363    114999
364     82990
365    109999
366     82990
367     79990
368    114990
369    129999
370    149990
371     71290
372     79500
373     82990
374     70980
375     99990
376     94000
377     82990
378     79990
379     85990
380     86990
381    105990
382     84990
383     59999
384     91999
385     78900
386    132790
387     60990
388     65556
389     70190
390     79590
391     65556
392     76990
393     65556
394     44990
395     84990
396     86999
397     78000
398     73063
399     73063
400    100990
401     74990
402     75990
403     84086
404     75990
405     77990
406     77990
407    179990
408    179990
409     82990
410     87990
411     84500
412     74190
413     64990
414    155411
415    125394
416     49990
417     46990
418     48990
419     59999
420     46990
421     52990
422     57999
423     52490
424     56990
425     61990
426     58090
427     56990
428     61597
429     81990
430     61249
431     58990
432     83990
433    291190
434    145990
435    179990
436     64990
437     46790
438     44599
439     72964
440     48790
441     56491
442     50990
443     55990
444     57990
445     52990
446     57990
447     56990
448     55490
449     62490
450     64990
451     59990
452     60190
453     54490
454     60990
455     55790
456     64990
457     58990
458     54990
459     71990
460     69900
461     65990
462     49990
463     58990
464     74590
465     58990
466     64990
467     66490
468     77900
469     67490
470     61990
471     58990
472     74999
473     68900
474     71695
475     62490
476     62317
477    207290
478     87990
479     73990
480     73990
481     73990
482     73990
483     73990
484     73990
485     57990
486     61990
487     79990
488     68990
489     85990
490     99990
491     77990
492     79990
493     93190
494     94990
495     84990
496     57990
497    102990
498     99990
499     94990
500    104000
501     76990
502     90190
503     88488
504    109990
505     86990
506     89990
507    239759
508     78990
509    121890
510     85990
511     94990
512     92000
513    162990
514    135300
515     64990
516    174527
517    162299
518    109190
519     99999
520    104990
521    109990
522     99990
523    244801
524     94990
525     86000
526    162399
527    119599
528    211753
529    110999
530     99990
531     81990
532     66990
533     84990
534    104990
535    134990
536     98990
537    144690
538     99990
539    119990
540    194990
541    124990
542    122410
543    179990
544    154990
545    122990
546    224990
547    279990
548    121990
549    116990
550    151098
551    129990
552    149999
553    139990
554    129990
555    171990
556     93955
557    234990
558    128500
559    102990
560    119990
561    120980
562    157249
563    229900
564    131500
565    154990
566    165990
567    119990
568    167990
569    165000
570     62990
571     85990
572     94990
573    136990
574    234990
575    159990
576    233990
577     93990
578    116941
579     63990
580     66990
581     82500
582    119990
583    159990
584     98912
585     92990
586    119990
587    169990
588    139990
589    192990
590    299990
591    269990
592    139990
593    265998
594    441990
595     86990
596    109990
597    109590
598    146490
599     85990
600    112990
601    104990
602    112990
603    132990
604    104990
605     85990
606    149990
607    125990
608    103990
609    101990
610    104990
611    131990
612    128990
613    184990
614    225990
615    124990
616    104990
617    149990
618    169990
619    225990
620    243990
621    309990
622    225990
623     45990
624     58100
625     62990
626     32990
627     33990
628     30990
629     36000
630     32990
631     35990
632     27990
633     25990
634     25990
635     30780
636     37990
637     35990
638     39490
639     36990
640     39990
641     33690
642     40590
643     37990
644     34500
645     36990
646     43490
647     41490
648     34990
649     44490
650     40590
651     42090
652     35990
653     39490
654     37390
655     52632
656     39990
657     43990
658     32917
659     34990
660     39990
661     41999
662     41990
663     44490
664     41990
665     44490
666     49990
667     44390
668     57990
669     56990
670     48990
671     49970
672     47990
673     48990
674     53990
675     52990
676     43990
677     59490
678     64990
679     47490
680     59990
681     69990
682     58990
683     59490
684     67500
685     48990
686     62450
687     58990
688     57999
689     56990
690     72990
691     65990
692     98020
693     63990
694     49890
695     49990
696     59490
697     73999
698     60990
699     76190
700     74798
701     58990
702     68100
703     77990
704     55090
705     91990
706     84208
707     44990
708     53490
709     76498
710     98920
711     54990
712     49990
713     52380
714     49990
715     52500
716     49990
717     75999
718     80990
719     59900
720     54590
721     75500
722     51890
723     78000
724     59999
725     64990
726     57900
727     81978
728     59990
729     49490
730     54990
731     68500
732     54990
733     54990
734     63990
735     80000
736     51990
737     62990
738     52990
739     75100
740     76990
741     79990
742     71990
743     71990
744     99990
745     79990
746     93990
747     82990
748    106990
749     92990
750     81490
751     56990
752     64990
753     60990
754     84988
755     90990
756     63990
757     63990
758     57999
759     72400
760     78990
761     59990
762    111990
763    109000
764     89990
765     78988
766     73138
767    106990
768     79990
769     89570
770     68500
771     73400
772     79990
773     84990
774     99990
775     72990
776     92990
777     84190
778    112990
779    114990
780     99990
781     95990
782    159990
783     76990
784    130990
785     99990
786    112990
787     77988
788     76000
789     99990
790    111000
791     84970
792     75990
793     89990
794     81990
795     80490
796    135990
797    154990
798    199990
799    114990
800    129990
801    114990
802    146990
803    104990
804    114990
805    124990
806    134990
807    141990
808    129990
809    142990
810    121990
811    124990
812    141990
813    162990
814    130500
815    116990
816    138990
817    234990
818    135990
819    144990
820    149990
821    142990
822     57490
Name: Price, dtype: int64

In [35]:
# Precio promedio de las laptops:
datos["Price"].mean()  # Devuelve el precio promedio
datos["Price"].min()   # Devuelve el precio de la computadora más barata
datos["Price"].max()   # Devuelve el precio de la computadora más cara
# Ojo! Solo imprime la última instrucción

441990

In [49]:
print("El precio promedio de las computadoras portátiles es {:.3f} +/- {:.3f} dólares".
      format(datos["Price"].mean(),datos["Price"].std()))

El precio promedio de las computadoras portátiles es 76745.177 +/- 45101.791 dólares

In [46]:
# Opcional: 
precio_promedio=datos["Price"].mean()
print(f"El precio promedio de las computadoras portátiles es {precio_promedio}")

El precio promedio de las computadoras portátiles es 76745.17739975698

In [56]:
# Opcional:
print("El precio promedio de las computadoras es: ", datos["Price"].mean())

El precio promedio de las computadoras es:  76745.17739975698

In [52]:
print("El precio promedio de las computadoras portátiles es {:.2f}".format(datos["Price"].mean()))
print("La computadora portátil más económica tiene un precio de {:.2f}".format(datos["Price"].min()))
print("La computadora portátil más cara tiene un precio de {:.2f}".format(datos["Price"].max()))

El precio promedio de las computadoras portátiles es 76745.18
La computadora portátil más económica tiene un precio de 16990.00
La computadora portátil más cara tiene un precio de 441990.00

In [54]:
datos.Price.std()

45101.790524689466

In [55]:
datos["Price"].sum()  # Devuelve la suma de los datos de la serie

63161281

# Filtrado de un DataFrame

In [62]:
# Solo me interesa una marca. ASUS.
datos[datos["brand"]=="ASUS"]  # Devuelve el dataframe de las laptops ASUS

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0
5,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
6,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21990,3 stars,31,3
7,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58799,3 stars,0,0
13,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,22990,3 stars,0,0
14,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,35990,3 stars,0,0
20,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,29890,4 stars,7,0
21,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,23990,3 stars,15279,1947
24,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,34429,4 stars,37,6
26,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,35990,4 stars,1479,181
27,ASUS,Intel,Core i3,10th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33980,4 stars,67,3
32,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,37990,4 stars,284,39
33,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,37890,4 stars,44,5
37,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
42,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,36990,4 stars,20,1
45,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,45990,4 stars,816,147
52,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38490,3 stars,19,3
60,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,0,0
66,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,39990,4 stars,181,19
68,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41990,3 stars,0,0
70,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,39990,3 stars,0,0
74,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,48490,3 stars,0,0
81,ASUS,Intel,Core i3,11th,4 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,36990,4 stars,70,9
83,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,48990,3 stars,0,0
84,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23490,4 stars,632,92
86,ASUS,Intel,Core i3,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,37990,4 stars,990,108
89,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,4 stars,130,12
90,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,30,4
91,ASUS,Intel,Core i3,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,Yes,Yes,51990,4 stars,6,2
92,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,48990,4 stars,174,30
93,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,40,7
98,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,39990,4 stars,2551,297
102,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,41990,3 stars,0,0
104,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,44990,4 stars,2058,305
107,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,42990,4 stars,74,11
112,ASUS,Intel,Core i3,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,44990,3 stars,0,0
117,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,51649,3 stars,0,0
119,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
120,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,42990,4 stars,1869,234
121,ASUS,Intel,Core i3,11th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,44890,3 stars,7,0
122,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,41490,4 stars,4008,519
125,ASUS,Intel,Core i3,10th,4 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,40990,4 stars,4008,519
130,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,32890,3 stars,28,4
136,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,35990,3 stars,17,0
139,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,34990,3 stars,4203,490
140,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38900,3 stars,13,0
148,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,35590,3 stars,12,1
150,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,38990,4 stars,1850,216
151,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,43,7
153,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,24990,4 stars,502,93
156,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38000,4 stars,7,0
160,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,41500,3 stars,4,0
163,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,21490,3 stars,818,113
165,ASUS,Intel,Core i3,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,32990,2 stars,12,0
166,ASUS,Intel,Core i3,11th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,38680,3 stars,17,1
167,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,23990,4 stars,974,170
169,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,33990,3 stars,31,6
170,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,20490,3 stars,637,91
174,ASUS,Intel,Core i3,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,41890,4 stars,53,6
180,ASUS,Intel,Core i3,10th,4 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,40990,3 stars,0,0
188,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,18990,3 stars,197,25
189,ASUS,Intel,Celeron Dual,Not Available,4 GB,LPDDR4,0 GB,512 GB,Windows,32-bit,0 GB,Casual,No warranty,No,No,17990,3 stars,1180,148
199,ASUS,Intel,Core i5,10th,8 GB,LPDDR4,0 GB,512 GB,DOS,32-bit,4 GB,Casual,No warranty,No,No,106167,4 stars,1881,241
208,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,48990,3 stars,0,0
213,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,49800,3 stars,0,0
219,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,No,57990,4 stars,3712,412
224,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,Yes,Yes,63990,4 stars,10,1
228,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,71990,4 stars,91,17
229,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,47990,4 stars,35,2
231,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,72990,4 stars,74,10
233,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,6 GB,Gaming,1 year,No,Yes,89990,4 stars,124,17
235,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,Yes,65990,4 stars,3850,378
239,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,65990,3 stars,0,0
241,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,73490,4 stars,213,45
246,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,59990,4 stars,11,2
247,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,6 GB,Casual,1 year,No,Yes,82990,4 stars,262,31
250,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,2 GB,ThinNlight,1 year,No,No,49990,4 stars,45,3
253,ASUS,Intel,Core i5,9th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,Yes,54990,4 stars,1681,227
258,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,Yes,47990,4 stars,1625,152
261,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,No,63990,3 stars,0,0
263,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,59990,3 stars,0,0
265,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,59990,3 stars,0,0
269,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,74990,3 stars,0,0
274,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,58990,3 stars,0,0
278,ASUS,Intel,Core i5,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,59990,3 stars,3,0
283,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,6 GB,Casual,1 year,No,No,84990,5 stars,5,0
291,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,105990,4 stars,59,11
295,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,84990,4 stars,10,2
299,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,72990,4 stars,76,14
302,ASUS,Intel,Core i5,10th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,79990,4 stars,11,3
305,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,53400,4 stars,46,6
320,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,No,64990,4 stars,4,0
327,ASUS,Intel,Core i5,8th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,72990,4 stars,44,4
329,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,57990,3 stars,0,0
337,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,73990,4 stars,32,6
339,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,99990,4 stars,35,6
343,ASUS,Intel,Core i5,8th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,53690,4 stars,19,3
345,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,53190,4 stars,11,0
349,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,84990,3 stars,0,0
351,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,99990,3 stars,0,0
352,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,84990,3 stars,0,0
359,ASUS,Intel,Core i5,11th,8 GB,LPDDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,84990,3 stars,0,0
362,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,6 GB,Casual,1 year,No,No,88990,3 stars,0,0
368,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,114990,3 stars,0,0
375,ASUS,Intel,Core i5,11th,8 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,99990,3 stars,0,0
379,ASUS,Intel,Core i5,8th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,85990,3 stars,0,0
380,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,2 GB,Casual,No warranty,No,No,86990,3 stars,0,0
381,ASUS,Intel,Core i5,10th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,2 GB,Casual,1 year,No,Yes,105990,5 stars,4,0
382,ASUS,Intel,Core i5,10th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,84990,3 stars,0,0
386,ASUS,Intel,Core i5,10th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,132790,3 stars,0,0
392,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,76990,3 stars,0,0
395,ASUS,Intel,Core i5,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,Yes,84990,3 stars,17,2
402,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,75990,4 stars,1365,137
404,ASUS,Intel,Core i5,11th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,75990,4 stars,368,48
405,ASUS,Intel,Core i5,11th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Gaming,1 year,No,Yes,77990,4 stars,202,26
406,ASUS,Intel,Core i5,10th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,77990,4 stars,187,26
409,ASUS,Intel,Core i5,10th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,82990,4 stars,844,118
410,ASUS,Intel,Core i5,11th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,1 year,No,No,87990,3 stars,0,0
411,ASUS,Intel,Core i5,11th,8 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Casual,No warranty,No,No,84500,4 stars,3,0
420,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,46990,4 stars,1444,179
427,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,56990,3 stars,0,0
429,ASUS,Intel,Core i5,8th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,81990,3 stars,0,0
430,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,61249,3 stars,0,0
432,ASUS,Intel,Core i5,10th,8 GB,DDR4,0 GB,1024 GB,Windows,64-bit,2 GB,Casual,No warranty,No,No,83990,3 stars,0,0
442,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,32-bit,0 GB,Casual,1 year,No,Yes,50990,4 stars,1188,127
443,ASUS,Intel,Core i5,10th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,55990,4 stars,23,0
445,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,52990,3 stars,0,0
450,ASUS,Intel,Core i5,11th,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,64990,4 stars,10,1
452,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,2 GB,Casual,1 year,No,Yes,60190,4 stars,33,4
453,ASUS,Intel,Core i5,9th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,54490,4 stars,343,47
456,ASUS,Intel,Core i5,11th,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,64990,4 stars,328,51
457,ASUS,Intel,Core i5,11th,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,58990,4 stars,6,1
462,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,49990,3 stars,22,2
465,ASUS,Intel,Core i5,10th,8 GB,DDR4,256 GB,1024 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,58990,5 stars,1,1
466,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,64990,3 stars,0,0
473,ASUS,Intel,Core i5,11th,8 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,68900,5 stars,6,1
485,ASUS,Intel,Core i7,10th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,No,57990,4 stars,76,9
486,ASUS,Intel,Core i7,10th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,61990,4 stars,11,2
491,ASUS,Intel,Core i7,11th,8 GB,DDR4,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,77990,4 stars,21,5
494,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,No,Yes,94990,3 stars,0,0
499,ASUS,Intel,Core i7,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,94990,4 stars,118,15
508,ASUS,Intel,Core i7,11th,16 GB,DDR4,512 GB,0 GB,Windows,64-bit,2 GB,Casual,1 year,No,Yes,78990,4 stars,35,4
510,ASUS,Intel,Core i7,8th,16 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,85990,4 stars,18,0
521,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,Yes,No,109990,3 stars,0,0
522,ASUS,Intel,Core i7,8th,16 GB,DDR3,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,99990,4 stars,30,7
524,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,94990,3 stars,0,0
531,ASUS,Intel,Core i7,8th,8 GB,LPDDR3,512 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,1 year,No,No,81990,4 stars,40,4
534,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,2 GB,Casual,1 year,Yes,Yes,104990,3 stars,0,0
535,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,134990,3 stars,0,0
536,ASUS,Intel,Core i7,11th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,98990,4 stars,445,56
538,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,99990,3 stars,0,0
540,ASUS,Intel,Core i7,11th,16 GB,DDR4,1024 GB,0 GB,Windows,32-bit,4 GB,Casual,1 year,No,No,194990,3 stars,0,0
541,ASUS,Intel,Core i7,10th,16 GB,LPDDR3,1024 GB,0 GB,Windows,64-bit,2 GB,Casual,1 year,No,Yes,124990,4 stars,17,1
546,ASUS,Intel,Core i7,10th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,6 GB,Casual,1 year,Yes,No,224990,4 stars,9,0
557,ASUS,Intel,Core i7,10th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,8 GB,Casual,No warranty,No,No,234990,3 stars,0,0
560,ASUS,Intel,Core i7,11th,16 GB,LPDDR4X,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,1 year,Yes,No,119990,4 stars,8,1
561,ASUS,Intel,Core i7,11th,16 GB,DDR4,1024 GB,0 GB,Windows,32-bit,6 GB,Casual,No warranty,No,No,120980,3 stars,0,0
562,ASUS,Intel,Core i7,11th,16 GB,DDR4,1024 GB,0 GB,Windows,32-bit,6 GB,Casual,1 year,No,No,157249,4 stars,7,0
564,ASUS,Intel,Core i7,11th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,6 GB,Casual,1 year,No,No,131500,3 stars,0,0
565,ASUS,Intel,Core i7,10th,16 GB,LPDDR3,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,154990,5 stars,3,0
566,ASUS,Intel,Core i7,10th,16 GB,LPDDR3,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,165990,3 stars,0,0
568,ASUS,Intel,Core i7,10th,16 GB,LPDDR3,1024 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,167990,3 stars,0,0
576,ASUS,Intel,Core i7,10th,16 GB,LPDDR3,2048 GB,0 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,233990,3 stars,0,0
577,ASUS,Intel,Core i7,10th,16 GB,DDR4,0 GB,1024 GB,Windows,64-bit,2 GB,Casual,No warranty,No,No,93990,3 stars,0,0
580,ASUS,Intel,Core i7,10th,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,4 GB,Gaming,No warranty,No,No,66990,4 stars,25,4
581,ASUS,Intel,Core i7,11th,16 GB,DDR4,256 GB,1024 GB,Windows,32-bit,0 GB,ThinNlight,No warranty,No,No,82500,3 stars,0,0
584,ASUS,Intel,Core i7,8th,16 GB,DDR4,256 GB,1024 GB,Windows,64-bit,0 GB,ThinNlight,No warranty,No,No,98912,3 stars,0,0
590,ASUS,Intel,Core i9,12th,16 GB,DDR5,1024 GB,0 GB,Windows,64-bit,6 GB,Casual,No warranty,No,No,299990,3 stars,0,0
591,ASUS,Intel,Core i9,10th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,6 GB,Casual,1 year,Yes,No,269990,4 stars,8,1
592,ASUS,Intel,Core i9,11th,16 GB,DDR4,1024 GB,0 GB,Windows,64-bit,6 GB,Gaming,1 year,No,No,139990,3 stars,0,0

In [63]:
#Si me interesa solo el precio
datos[datos["brand"]=="ASUS"]["Price"]  # Devuelve el precio de las laptops ASUS

0       34649
3       69990
4       26990
5       22990
6       21990
7       58799
13      22990
14      35990
20      29890
21      23990
24      34429
26      35990
27      33980
32      37990
33      37890
37      45990
42      36990
45      45990
52      38490
60      35990
66      39990
68      41990
70      39990
74      48490
81      36990
83      48990
84      23490
86      37990
89      35990
90      42990
91      51990
92      48990
93      42990
98      39990
102     41990
104     44990
107     42990
112     44990
117     51649
119     40990
120     42990
121     44890
122     41490
125     40990
130     32890
136     35990
139     34990
140     38900
148     35590
150     38990
151     33990
153     24990
156     38000
160     41500
163     21490
165     32990
166     38680
167     23990
169     33990
170     20490
174     41890
180     40990
188     18990
189     17990
199    106167
208     48990
213     49800
219     57990
224     63990
228     71990
229     47990
231     72990
233     89990
235     65990
239     65990
241     73490
246     59990
247     82990
250     49990
253     54990
258     47990
261     63990
263     59990
265     59990
269     74990
274     58990
278     59990
283     84990
291    105990
295     84990
299     72990
302     79990
305     53400
320     64990
327     72990
329     57990
337     73990
339     99990
343     53690
345     53190
349     84990
351     99990
352     84990
359     84990
362     88990
368    114990
375     99990
379     85990
380     86990
381    105990
382     84990
386    132790
392     76990
395     84990
402     75990
404     75990
405     77990
406     77990
409     82990
410     87990
411     84500
420     46990
427     56990
429     81990
430     61249
432     83990
442     50990
443     55990
445     52990
450     64990
452     60190
453     54490
456     64990
457     58990
462     49990
465     58990
466     64990
473     68900
485     57990
486     61990
491     77990
494     94990
499     94990
508     78990
510     85990
521    109990
522     99990
524     94990
531     81990
534    104990
535    134990
536     98990
538     99990
540    194990
541    124990
546    224990
557    234990
560    119990
561    120980
562    157249
564    131500
565    154990
566    165990
568    167990
576    233990
577     93990
580     66990
581     82500
584     98912
590    299990
591    269990
592    139990
594    441990
598    146490
623     45990
624     58100
625     62990
627     33990
630     32990
632     27990
633     25990
634     25990
635     30780
637     35990
641     33690
643     37990
644     34500
686     62450
687     58990
689     56990
694     49890
701     58990
705     91990
716     49990
718     80990
723     78000
730     54990
732     54990
733     54990
737     62990
739     75100
740     76990
741     79990
742     71990
743     71990
745     79990
747     82990
748    106990
749     92990
751     56990
756     63990
759     72400
762    111990
768     79990
775     72990
778    112990
779    114990
781     95990
783     76990
785     99990
786    112990
788     76000
789     99990
790    111000
791     84970
796    135990
797    154990
798    199990
799    114990
800    129990
801    114990
803    104990
804    114990
805    124990
806    134990
808    129990
809    142990
810    121990
811    124990
812    141990
813    162990
814    130500
815    116990
816    138990
817    234990
818    135990
819    144990
820    149990
821    142990
Name: Price, dtype: int64

In [65]:
# El precio promedio de venta de las computadoras ASUS
print("Precio promedio de las laptops marca ASUS {:.2f} ".format(datos[datos["brand"]=="ASUS"]["Price"].mean()))

Precio promedio de las laptops marca ASUS 78937.60

In [66]:
# El precio promedio de venta de las computadoras HP
print("Precio promedio de las laptops marca HP {:.2f} ".format(datos[datos["brand"]=="HP"]["Price"].mean()))

Precio promedio de las laptops marca HP 73640.27

In [67]:
# El precio promedio de venta de las computadoras DELL
print("Precio promedio de las laptops marca DELL {:.2f} ".format(datos[datos["brand"]=="DELL"]["Price"].mean()))

Precio promedio de las laptops marca DELL 60934.66

Para simplificar el trabajo no vamos a apoyar de un loop for... para hacer el cálculo
de manera individual por marca.

In [69]:
datos["brand"].unique()   # Marcas en mi dataframe

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [70]:
marcas=datos["brand"].unique()   # Marcas en mi dataframe

In [71]:
marcas

array(['ASUS', 'Lenovo', 'acer', 'Avita', 'HP', 'DELL', 'MSI', 'APPLE'],
      dtype=object)

In [73]:
for marca in marcas:
    print("El precio promedio de las laptops marca {} es {:.2f} ".format(marca,datos[datos["brand"]==marca]["Price"].mean()))

El precio promedio de las laptops marca ASUS es 78937.60
El precio promedio de las laptops marca Lenovo es 72920.21
El precio promedio de las laptops marca acer es 72420.04
El precio promedio de las laptops marca Avita es 65157.43
El precio promedio de las laptops marca HP es 73640.27
El precio promedio de las laptops marca DELL es 60934.66
El precio promedio de las laptops marca MSI es 98713.02
El precio promedio de las laptops marca APPLE es 151707.86

In [ ]:
# Repetir este ejercicio de calcular el precio promedio de venta, pero ahora por 
# capacidad de memoria RAM.
# Cuál es el precio de venta de una computadora con 4 GB en ram?
# Cuál es el precio de venta de una computadora con 8 GB en ram?
# Cuál es el precio de venta de una computadora con 16 GB en ram?
# Cuál es el precio de venta de una computadora con 32 GB en ram?

# Operaciones entre columnas de un DataFrame

In [76]:
# Supongamos que el precio de venta es con impuestos... cómo obtengo los precios
# de las laptops antes de impuestos.. suponiendo un impuesto de 16%

datos["Price"]/1.16

0       29869.827586
1       33619.827586
2       34481.896552
3       60336.206897
4       23267.241379
5       19818.965517
6       18956.896552
7       50688.793103
8       43102.586207
9       51715.517241
10      80775.862069
11      62922.413793
12      15077.586207
13      19818.965517
14      31025.862069
15      48698.275862
16      56370.689655
17      27585.344828
18      28008.620690
19      27412.931034
20      25767.241379
21      20681.034483
22      28409.482759
23      39827.586207
24      29680.172414
25      32750.000000
26      31025.862069
27      29293.103448
28      34474.137931
29      34043.103448
30      46543.103448
31      33612.068966
32      32750.000000
33      32663.793103
34      33612.068966
35      32750.000000
36      36198.275862
37      39646.551724
38      34474.137931
39      36629.310345
40      31887.931034
41      46543.103448
42      31887.931034
43      33568.965517
44      34043.103448
45      39646.551724
46      34481.896552
47      37060.344828
48      43094.827586
49      35767.241379
50      36198.275862
51      36198.275862
52      33181.034483
53      33612.068966
54      38784.482759
55      31456.896552
56      33594.827586
57      38706.896552
58      33612.068966
59      38299.137931
60      31025.862069
61      34655.172414
62      35336.206897
63      36629.310345
64      20681.034483
65      62068.103448
66      34474.137931
67      36205.172414
68      36198.275862
69      34481.896552
70      34474.137931
71      34481.034483
72      36629.310345
73      36198.275862
74      41801.724138
75      38255.172414
76      37844.827586
77      40250.000000
78      35336.206897
79      34474.137931
80      37922.413793
81      31887.931034
82      41810.344828
83      42232.758621
84      20250.000000
85      46756.896552
86      32750.000000
87      37060.344828
88      37060.344828
89      31025.862069
90      37060.344828
91      44818.965517
92      42232.758621
93      37060.344828
94      33612.068966
95      39646.551724
96      36629.310345
97      37905.172414
98      34474.137931
99      42232.758621
100     47405.172414
101     35336.206897
102     36198.275862
103     47405.172414
104     38784.482759
105     35560.344828
106     38784.482759
107     37060.344828
108     52405.172414
109     39353.448276
110     36198.275862
111     39215.517241
112     38784.482759
113     37060.344828
114     39215.517241
115     33447.413793
116     59712.931034
117     44525.000000
118     41370.689655
119     35336.206897
120     37060.344828
121     38698.275862
122     35767.241379
123     43956.896552
124     42155.172414
125     35336.206897
126     36025.862069
127     49999.137931
128     39594.827586
129     47836.206897
130     28353.448276
131     31025.862069
132     36629.310345
133     36370.689655
134     34043.103448
135     37663.793103
136     31025.862069
137     37758.620690
138     33612.068966
139     30163.793103
140     33534.482759
141     34474.137931
142     35250.000000
143     31887.931034
144     34474.137931
145     36198.275862
146     37905.172414
147     34301.724138
148     30681.034483
149     31456.896552
150     33612.068966
151     29301.724138
152     37413.793103
153     21543.103448
154     35129.310345
155     37068.965517
156     32758.620690
157     32750.000000
158     42481.896552
159     33619.827586
160     35775.862069
161     31895.689655
162     36982.758621
163     18525.862069
164     35758.620690
165     28439.655172
166     33344.827586
167     20681.034483
168     34818.965517
169     29301.724138
170     17663.793103
171     35767.241379
172     39215.517241
173     38353.448276
174     36112.068966
175     37060.344828
176     35336.206897
177     42232.758621
178     37577.586207
179     38525.862069
180     35336.206897
181     37922.413793
182     37577.586207
183     35681.034483
184     38181.034483
185     42240.517241
186     34474.137931
187     39991.379310
188     16370.689655
189     15508.620690
190     22818.965517
191     24129.310345
192     25861.206897
193     22405.172414
194     14646.551724
195     21543.103448
196     43956.896552
197    103439.655172
198     81198.275862
199     91523.275862
200     58698.275862
201    120681.034483
202     48267.241379
203     88406.034483
204     40508.620690
205     65527.586207
206     42663.793103
207     74885.344828
208     42232.758621
209     48267.241379
210     70687.931034
211    117750.000000
212     51284.482759
213     42931.034483
214     53447.413793
215     47405.172414
216     46543.103448
217     45681.034483
218     58612.068966
219     49991.379310
220     53706.896552
221     45681.034483
222     44818.965517
223     53439.655172
224     55163.793103
225     56887.931034
226     45681.034483
227     43094.827586
228     62060.344828
229     41370.689655
230     41801.724138
231     62922.413793
232     66370.689655
233     77577.586207
234     51715.517241
235     56887.931034
236     62060.344828
237     61974.137931
238     56025.862069
239     56887.931034
240     48275.000000
241     63353.448276
242     64215.517241
243     50293.103448
244     48275.000000
245     58612.068966
246     51715.517241
247     71543.103448
248     55336.206897
249     60422.413793
250     43094.827586
251     47836.206897
252     84474.137931
253     47405.172414
254     51715.517241
255     46543.103448
256     57757.758621
257     52577.586207
258     41370.689655
259     51723.275862
260     68956.896552
261     55163.793103
262     55163.793103
263     51715.517241
264     48267.241379
265     51715.517241
266     55163.793103
267     59905.172414
268     77060.344828
269     64646.551724
270     56025.862069
271     57318.965517
272     77329.310345
273     61198.275862
274     50853.448276
275     49568.965517
276     68956.896552
277     48742.241379
278     51715.517241
279     56025.862069
280     52836.206897
281     47405.172414
282     51715.517241
283     73267.241379
284     62500.000000
285     51715.517241
286     75853.448276
287     49991.379310
288     59905.172414
289     59474.137931
290     67232.758621
291     91370.689655
292     68956.896552
293     47836.206897
294     60336.206897
295     73267.241379
296     51715.517241
297     96456.896552
298     56887.931034
299     62922.413793
300     61284.482759
301     64646.551724
302     68956.896552
303     47836.206897
304     57318.965517
305     46034.482759
306     64224.137931
307     99129.310345
308     53439.655172
309    137922.413793
310    148353.448276
311     64646.551724
312     48698.275862
313    126724.137931
314     48267.241379
315     67232.758621
316     91801.724138
317     61198.275862
318     56025.862069
319     49991.379310
320     56025.862069
321     47405.172414
322     96550.862069
323     61032.758621
324     51715.517241
325     85775.862069
326     48267.241379
327     62922.413793
328     56025.862069
329     49991.379310
330     66370.689655
331     54308.620690
332     67232.758621
333     99129.310345
334     56887.931034
335     76715.517241
336     97922.413793
337     63784.482759
338     52586.206897
339     86198.275862
340     58612.068966
341     61033.620690
342     56887.931034
343     46284.482759
344     48267.241379
345     45853.448276
346     50861.206897
347     62060.344828
348     70689.655172
349     73267.241379
350     77584.482759
351     86198.275862
352     73267.241379
353     60257.758621
354     68956.896552
355     65775.862069
356     48275.000000
357     62844.827586
358     63784.482759
359     73267.241379
360     63378.448276
361    108620.689655
362     76715.517241
363     99137.068966
364     71543.103448
365     94826.724138
366     71543.103448
367     68956.896552
368     99129.310345
369    112068.103448
370    129301.724138
371     61456.896552
372     68534.482759
373     71543.103448
374     61189.655172
375     86198.275862
376     81034.482759
377     71543.103448
378     68956.896552
379     74129.310345
380     74991.379310
381     91370.689655
382     73267.241379
383     51723.275862
384     79309.482759
385     68017.241379
386    114474.137931
387     52577.586207
388     56513.793103
389     60508.620690
390     68612.068966
391     56513.793103
392     66370.689655
393     56513.793103
394     38784.482759
395     73267.241379
396     74999.137931
397     67241.379310
398     62985.344828
399     62985.344828
400     87060.344828
401     64646.551724
402     65508.620690
403     72487.931034
404     65508.620690
405     67232.758621
406     67232.758621
407    155163.793103
408    155163.793103
409     71543.103448
410     75853.448276
411     72844.827586
412     63956.896552
413     56025.862069
414    133975.000000
415    108098.275862
416     43094.827586
417     40508.620690
418     42232.758621
419     51723.275862
420     40508.620690
421     45681.034483
422     49999.137931
423     45250.000000
424     49129.310345
425     53439.655172
426     50077.586207
427     49129.310345
428     53100.862069
429     70681.034483
430     52800.862069
431     50853.448276
432     72405.172414
433    251025.862069
434    125853.448276
435    155163.793103
436     56025.862069
437     40336.206897
438     38447.413793
439     62900.000000
440     42060.344828
441     48699.137931
442     43956.896552
443     48267.241379
444     49991.379310
445     45681.034483
446     49991.379310
447     49129.310345
448     47836.206897
449     53870.689655
450     56025.862069
451     51715.517241
452     51887.931034
453     46974.137931
454     52577.586207
455     48094.827586
456     56025.862069
457     50853.448276
458     47405.172414
459     62060.344828
460     60258.620690
461     56887.931034
462     43094.827586
463     50853.448276
464     64301.724138
465     50853.448276
466     56025.862069
467     57318.965517
468     67155.172414
469     58181.034483
470     53439.655172
471     50853.448276
472     64654.310345
473     59396.551724
474     61806.034483
475     53870.689655
476     53721.551724
477    178698.275862
478     75853.448276
479     63784.482759
480     63784.482759
481     63784.482759
482     63784.482759
483     63784.482759
484     63784.482759
485     49991.379310
486     53439.655172
487     68956.896552
488     59474.137931
489     74129.310345
490     86198.275862
491     67232.758621
492     68956.896552
493     80336.206897
494     81887.931034
495     73267.241379
496     49991.379310
497     88784.482759
498     86198.275862
499     81887.931034
500     89655.172414
501     66370.689655
502     77750.000000
503     76282.758621
504     94818.965517
505     74991.379310
506     77577.586207
507    206688.793103
508     68094.827586
509    105077.586207
510     74129.310345
511     81887.931034
512     79310.344828
513    140508.620690
514    116637.931034
515     56025.862069
516    150454.310345
517    139912.931034
518     94129.310345
519     86206.034483
520     90508.620690
521     94818.965517
522     86198.275862
523    211035.344828
524     81887.931034
525     74137.931034
526    139999.137931
527    103102.586207
528    182545.689655
529     95688.793103
530     86198.275862
531     70681.034483
532     57750.000000
533     73267.241379
534     90508.620690
535    116370.689655
536     85336.206897
537    124732.758621
538     86198.275862
539    103439.655172
540    168094.827586
541    107750.000000
542    105525.862069
543    155163.793103
544    133612.068966
545    106025.862069
546    193956.896552
547    241370.689655
548    105163.793103
549    100853.448276
550    130256.896552
551    112060.344828
552    129309.482759
553    120681.034483
554    112060.344828
555    148267.241379
556     80995.689655
557    202577.586207
558    110775.862069
559     88784.482759
560    103439.655172
561    104293.103448
562    135559.482759
563    198189.655172
564    113362.068966
565    133612.068966
566    143094.827586
567    103439.655172
568    144818.965517
569    142241.379310
570     54301.724138
571     74129.310345
572     81887.931034
573    118094.827586
574    202577.586207
575    137922.413793
576    201715.517241
577     81025.862069
578    100811.206897
579     55163.793103
580     57750.000000
581     71120.689655
582    103439.655172
583    137922.413793
584     85268.965517
585     80163.793103
586    103439.655172
587    146543.103448
588    120681.034483
589    166370.689655
590    258612.068966
591    232750.000000
592    120681.034483
593    229308.620690
594    381025.862069
595     74991.379310
596     94818.965517
597     94474.137931
598    126284.482759
599     74129.310345
600     97405.172414
601     90508.620690
602     97405.172414
603    114646.551724
604     90508.620690
605     74129.310345
606    129301.724138
607    108612.068966
608     89646.551724
609     87922.413793
610     90508.620690
611    113784.482759
612    111198.275862
613    159474.137931
614    194818.965517
615    107750.000000
616     90508.620690
617    129301.724138
618    146543.103448
619    194818.965517
620    210336.206897
621    267232.758621
622    194818.965517
623     39646.551724
624     50086.206897
625     54301.724138
626     28439.655172
627     29301.724138
628     26715.517241
629     31034.482759
630     28439.655172
631     31025.862069
632     24129.310345
633     22405.172414
634     22405.172414
635     26534.482759
636     32750.000000
637     31025.862069
638     34043.103448
639     31887.931034
640     34474.137931
641     29043.103448
642     34991.379310
643     32750.000000
644     29741.379310
645     31887.931034
646     37491.379310
647     35767.241379
648     30163.793103
649     38353.448276
650     34991.379310
651     36284.482759
652     31025.862069
653     34043.103448
654     32232.758621
655     45372.413793
656     34474.137931
657     37922.413793
658     28376.724138
659     30163.793103
660     34474.137931
661     36206.034483
662     36198.275862
663     38353.448276
664     36198.275862
665     38353.448276
666     43094.827586
667     38267.241379
668     49991.379310
669     49129.310345
670     42232.758621
671     43077.586207
672     41370.689655
673     42232.758621
674     46543.103448
675     45681.034483
676     37922.413793
677     51284.482759
678     56025.862069
679     40939.655172
680     51715.517241
681     60336.206897
682     50853.448276
683     51284.482759
684     58189.655172
685     42232.758621
686     53836.206897
687     50853.448276
688     49999.137931
689     49129.310345
690     62922.413793
691     56887.931034
692     84500.000000
693     55163.793103
694     43008.620690
695     43094.827586
696     51284.482759
697     63792.241379
698     52577.586207
699     65681.034483
700     64481.034483
701     50853.448276
702     58706.896552
703     67232.758621
704     47491.379310
705     79301.724138
706     72593.103448
707     38784.482759
708     46112.068966
709     65946.551724
710     85275.862069
711     47405.172414
712     43094.827586
713     45155.172414
714     43094.827586
715     45258.620690
716     43094.827586
717     65516.379310
718     69818.965517
719     51637.931034
720     47060.344828
721     65086.206897
722     44732.758621
723     67241.379310
724     51723.275862
725     56025.862069
726     49913.793103
727     70670.689655
728     51715.517241
729     42663.793103
730     47405.172414
731     59051.724138
732     47405.172414
733     47405.172414
734     55163.793103
735     68965.517241
736     44818.965517
737     54301.724138
738     45681.034483
739     64741.379310
740     66370.689655
741     68956.896552
742     62060.344828
743     62060.344828
744     86198.275862
745     68956.896552
746     81025.862069
747     71543.103448
748     92232.758621
749     80163.793103
750     70250.000000
751     49129.310345
752     56025.862069
753     52577.586207
754     73265.517241
755     78439.655172
756     55163.793103
757     55163.793103
758     49999.137931
759     62413.793103
760     68094.827586
761     51715.517241
762     96543.103448
763     93965.517241
764     77577.586207
765     68093.103448
766     63050.000000
767     92232.758621
768     68956.896552
769     77215.517241
770     59051.724138
771     63275.862069
772     68956.896552
773     73267.241379
774     86198.275862
775     62922.413793
776     80163.793103
777     72577.586207
778     97405.172414
779     99129.310345
780     86198.275862
781     82750.000000
782    137922.413793
783     66370.689655
784    112922.413793
785     86198.275862
786     97405.172414
787     67231.034483
788     65517.241379
789     86198.275862
790     95689.655172
791     73250.000000
792     65508.620690
793     77577.586207
794     70681.034483
795     69387.931034
796    117232.758621
797    133612.068966
798    172405.172414
799     99129.310345
800    112060.344828
801     99129.310345
802    126715.517241
803     90508.620690
804     99129.310345
805    107750.000000
806    116370.689655
807    122405.172414
808    112060.344828
809    123267.241379
810    105163.793103
811    107750.000000
812    122405.172414
813    140508.620690
814    112500.000000
815    100853.448276
816    119818.965517
817    202577.586207
818    117232.758621
819    124991.379310
820    129301.724138
821    123267.241379
822     49560.344828
Name: Price, dtype: float64

In [77]:
# Cómo creamos una nueva serie en el DataFrame
datos["Price before taxes"]=datos["Price"]/1.16

In [78]:
datos.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,graphic_card_gb,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,Price before taxes
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,34649,2 stars,3,0,29869.827586
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,38999,3 stars,65,5,33619.827586
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,39999,3 stars,8,1,34481.896552
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,2 GB,Casual,No warranty,No,No,69990,3 stars,0,0,60336.206897
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,0 GB,Casual,No warranty,No,No,26990,3 stars,0,0,23267.241379

In [79]:
# Cuánto paga la tienda por impuestos en la venta de computadoras
datos["Taxes"]=datos["Price"]-datos["Price before taxes"]
datos.head()

,brand,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,os_bit,...,weight,warranty,Touchscreen,msoffice,Price,rating,Number of Ratings,Number of Reviews,Price before taxes,Taxes
0,ASUS,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,34649,2 stars,3,0,29869.827586,4779.172414
1,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,38999,3 stars,65,5,33619.827586,5379.172414
2,Lenovo,Intel,Core i3,10th,4 GB,DDR4,0 GB,1024 GB,Windows,64-bit,...,Casual,No warranty,No,No,39999,3 stars,8,1,34481.896552,5517.103448
3,ASUS,Intel,Core i5,10th,8 GB,DDR4,512 GB,0 GB,Windows,32-bit,...,Casual,No warranty,No,No,69990,3 stars,0,0,60336.206897,9653.793103
4,ASUS,Intel,Celeron Dual,Not Available,4 GB,DDR4,0 GB,512 GB,Windows,64-bit,...,Casual,No warranty,No,No,26990,3 stars,0,0,23267.241379,3722.758621

In [80]:
datos["Taxes"].sum()  # Cantidad total a pagar por impuestos

8711900.827586202

In [81]:
datos["Taxes"].mean() # Impuestos promedio

10585.541710311309

# Ordenar un DataFrame
Sintaxis:

nombre_dataframe.sort_values(by="nombre_serie")


IMPORTANTE: Estos cambios no afectan el dataframe original, solo aplican para desplegar el
resultado en la pantalla. Si se desea que los cambios se apliquen al DataFrame original
se debe emplear el parámetro _inplace_=True

In [82]:
datos.sort_values(by="brand")  # Ordena por marca en orden creciente

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
609   APPLE              M1             M1            10th   8 GB     DDR4
604   APPLE              M1             M1            10th  16 GB     DDR4
605   APPLE              M1             M1            10th   8 GB     DDR4
606   APPLE              M1             M1            10th  16 GB     DDR4
607   APPLE              M1             M1            10th   8 GB     DDR4
309   APPLE           Intel        Core i5            10th   8 GB  LPDDR4X
310   APPLE           Intel        Core i5             8th   8 GB     DDR3
608   APPLE              M1             M1            10th   8 GB     DDR4
621   APPLE              M1             M1            10th  32 GB     DDR4
610   APPLE              M1             M1            10th   8 GB     DDR4
611   APPLE              M1             M1            10th   8 GB     DDR4
612   APPLE              M1             M1            10th  16 GB     DDR4
613   APPLE              M1             M1            10th  16 GB     DDR4
614   APPLE              M1             M1            10th  16 GB     DDR4
615   APPLE              M1             M1            10th   4 GB     DDR4
616   APPLE              M1             M1            10th   8 GB     DDR4
617   APPLE              M1             M1            10th   8 GB     DDR4
618   APPLE              M1             M1            10th  16 GB     DDR4
603   APPLE              M1             M1            10th  16 GB     DDR4
619   APPLE              M1             M1            10th  16 GB     DDR4
602   APPLE              M1             M1            10th   8 GB     DDR4
600   APPLE              M1             M1            10th   8 GB     DDR4
408   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
407   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
601   APPLE              M1             M1            10th  16 GB     DDR4
620   APPLE              M1             M1            10th  16 GB     DDR4
622   APPLE              M1             M1            10th  16 GB     DDR4
599   APPLE              M1             M1            10th   8 GB     DDR4
465    ASUS           Intel        Core i5            10th   8 GB     DDR4
462    ASUS           Intel        Core i5            11th   8 GB     DDR4
457    ASUS           Intel        Core i5            11th  16 GB     DDR4
456    ASUS           Intel        Core i5            11th  16 GB     DDR4
473    ASUS           Intel        Core i5            11th   8 GB     DDR4
452    ASUS           Intel        Core i5            11th   8 GB     DDR4
450    ASUS           Intel        Core i5            11th  16 GB     DDR4
445    ASUS           Intel        Core i5            11th   8 GB     DDR4
443    ASUS           Intel        Core i5            10th   8 GB     DDR4
442    ASUS           Intel        Core i5            11th   8 GB     DDR4
432    ASUS           Intel        Core i5            10th   8 GB     DDR4
466    ASUS           Intel        Core i5            11th   8 GB     DDR4
453    ASUS           Intel        Core i5             9th   8 GB     DDR4
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
485    ASUS           Intel        Core i7            10th  16 GB     DDR4
540    ASUS           Intel        Core i7            11th  16 GB     DDR4
538    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
536    ASUS           Intel        Core i7            11th  16 GB     DDR4
535    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
534    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
531    ASUS           Intel        Core i7             8th   8 GB   LPDDR3
524    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
522    ASUS           Intel        Core i7             8th  16 GB     DDR3
521    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
510    ASUS           Intel        Core i7             8th  16 GB   LPDDR3
508    ASUS           Intel        Core i7            11th  16 GB     DDR4
499    ASUS           Intel        Core i7            11th  16 GB     DDR4
494    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
491    ASUS           Intel        Core i7            11th   8 GB     DDR4
486    ASUS           Intel        Core i7            10th   8 GB     DDR4
430    ASUS           Intel        Core i5            10th   8 GB     DDR4
429    ASUS           Intel        Core i5             8th   8 GB     DDR4
420    ASUS           Intel        Core i5            10th   8 GB     DDR4
541    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
302    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
299    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
295    ASUS           Intel        Core i5            11th   8 GB     DDR4
291    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
283    ASUS           Intel        Core i5            11th   8 GB     DDR4
278    ASUS           Intel        Core i5            11th  16 GB     DDR4
274    ASUS           Intel        Core i5            11th  16 GB     DDR4
269    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
265    ASUS           Intel        Core i5            11th  16 GB     DDR4
263    ASUS           Intel        Core i5            11th  16 GB     DDR4
261    ASUS           Intel        Core i5            10th   8 GB     DDR4
305    ASUS           Intel        Core i5            11th   8 GB     DDR4
258    ASUS           Intel        Core i5            10th   8 GB     DDR4
250    ASUS           Intel        Core i5            10th   8 GB     DDR4
247    ASUS           Intel        Core i5            11th  16 GB     DDR4
246    ASUS           Intel        Core i5            11th  16 GB     DDR4
241    ASUS           Intel        Core i5            11th  16 GB     DDR4
239    ASUS           Intel        Core i5            11th  16 GB     DDR4
235    ASUS           Intel        Core i5            10th   8 GB     DDR4
233    ASUS           Intel        Core i5            11th  16 GB     DDR4
231    ASUS           Intel        Core i5            11th   8 GB     DDR4
229    ASUS           Intel        Core i5            10th   8 GB     DDR4
228    ASUS           Intel        Core i5            11th   8 GB     DDR4
224    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
253    ASUS           Intel        Core i5             9th   8 GB     DDR4
320    ASUS           Intel        Core i5            10th   8 GB     DDR4
327    ASUS           Intel        Core i5             8th   8 GB   LPDDR3
329    ASUS           Intel        Core i5            11th   8 GB     DDR4
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
410    ASUS           Intel        Core i5            11th   8 GB     DDR4
409    ASUS           Intel        Core i5            10th   8 GB     DDR4
406    ASUS           Intel        Core i5            10th   8 GB     DDR4
405    ASUS           Intel        Core i5            11th   8 GB     DDR4
404    ASUS           Intel        Core i5            11th   8 GB     DDR4
402    ASUS           Intel        Core i5            10th   8 GB     DDR4
395    ASUS           Intel        Core i5            11th   8 GB     DDR4
392    ASUS           Intel        Core i5            11th   8 GB     DDR4
386    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
382    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
381    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
380    ASUS           Intel        Core i5            10th   8 GB     DDR4
379    ASUS           Intel        Core i5             8th   8 GB     DDR4
375    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
368    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
362    ASUS           Intel        Core i5            11th   8 GB     DDR4
359    ASUS           Intel        Core i5            11th   8 GB   LPDDR4
352    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
351    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
349    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
345    ASUS           Intel        Core i5            11th   8 GB     DDR4
343    ASUS           Intel        Core i5             8th   8 GB     DDR4
339    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
337    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
427    ASUS           Intel        Core i5            10th   8 GB     DDR4
546    ASUS           Intel        Core i7            10th  16 GB     DDR4
581    ASUS           Intel        Core i7            11th  16 GB     DDR4
560    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
790    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
789    ASUS             AMD        Ryzen 7   Not Available   4 GB  LPDDR4X
788    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
786    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
785    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
783    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
781    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
779    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
778    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
775    ASUS             AMD        Ryzen 7   Not Available   8 GB  LPDDR4X
768    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
762    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
759    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
756    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
751    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
749    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
748    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
747    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
745    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
791    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
796    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
797    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
798    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
817    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
816    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
815    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
814    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
813    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
812    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
743    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
811    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
809    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
808    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
806    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
805    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
804    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
803    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
801    ASUS             AMD        Ryzen 9   Not Available  16 GB  LPDDR4X
800    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
799    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
810    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
557    ASUS           Intel        Core i7            10th  16 GB     DDR4
742    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
740    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
625    ASUS           Intel   Pentium Quad   Not Available   8 GB  LPDDR4X
624    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
623    ASUS           Intel   Pentium Quad   Not Available   4 GB  LPDDR4X
598    ASUS           Intel        Core i7            10th  16 GB  LPDDR4X
594    ASUS           Intel        Core i9            11th  16 GB     DDR4
592    ASUS           Intel        Core i9            11th  16 GB     DDR4
591    ASUS           Intel        Core i9            10th  16 GB     DDR4
590    ASUS           Intel        Core i9            12th  16 GB     DDR5
584    ASUS           Intel        Core i7             8th  16 GB     DDR4
219    ASUS           Intel        Core i5            10th   8 GB     DDR4
580    ASUS           Intel        Core i7            10th  16 GB     DDR4
577    ASUS           Intel        Core i7            10th  16 GB     DDR4
576    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
568    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
566    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
565    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
564    ASUS           Intel        Core i7            11th  16 GB     DDR4
562    ASUS           Intel        Core i7            11th  16 GB     DDR4
561    ASUS           Intel        Core i7            11th  16 GB     DDR4
627    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
630    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
632    ASUS           Intel   Pentium Quad   Not Available   4 GB   LPDDR4
633    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
739    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
737    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
733    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
732    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
730    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
723    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
718    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
716    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
705    ASUS             AMD        Ryzen 5   Not Available   4 GB  LPDDR4X
741    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
701    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
689    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
687    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
686    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
644    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
643    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
641    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
637    ASUS             AMD        Ryzen 3   Not Available   8 GB     DDR4
635    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
634    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
694    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
213    ASUS           Intel        Core i5            11th   8 GB     DDR4
411    ASUS           Intel        Core i5            11th   8 GB     DDR4
170    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
140    ASUS           Intel        Core i3            11th   8 GB     DDR4
139    ASUS           Intel        Core i3            10th   4 GB     DDR4
102    ASUS           Intel        Core i3            11th   8 GB     DDR4
165    ASUS           Intel        Core i3            10th   8 GB     DDR4
42     ASUS           Intel        Core i3            11th   8 GB     DDR4
166    ASUS           Intel        Core i3            11th   8 GB     DDR4
136    ASUS           Intel        Core i3            10th   4 GB     DDR4
32     ASUS           Intel        Core i3            11th   8 GB     DDR4
167    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
120    ASUS           Intel        Core i3            10th   4 GB     DDR4
26     ASUS           Intel        Core i3            11th   4 GB     DDR4
117    ASUS           Intel        Core i3            11th   4 GB     DDR4
68     ASUS           Intel        Core i3            11th   4 GB     DDR4
98     ASUS           Intel        Core i3            10th   4 GB     DDR4
24     ASUS           Intel        Core i3            11th   4 GB     DDR4
174    ASUS           Intel        Core i3            11th   8 GB     DDR4
27     ASUS           Intel        Core i3            10th   8 GB     DDR4
93     ASUS           Intel        Core i3            11th   8 GB     DDR4
33     ASUS           Intel        Core i3            11th   8 GB     DDR4
104    ASUS           Intel        Core i3            11th   8 GB     DDR4
153    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
121    ASUS           Intel        Core i3            11th   4 GB     DDR4
37     ASUS           Intel        Core i3            11th   8 GB     DDR4
122    ASUS           Intel        Core i3            10th   4 GB     DDR4
52     ASUS           Intel        Core i3            11th   8 GB     DDR4
151    ASUS           Intel        Core i3            10th   4 GB     DDR4
119    ASUS           Intel        Core i3            10th   4 GB     DDR4
163    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
160    ASUS           Intel        Core i3            11th   8 GB     DDR4
150    ASUS           Intel        Core i3            10th   4 GB     DDR4
148    ASUS           Intel        Core i3            10th   4 GB     DDR4
125    ASUS           Intel        Core i3            10th   4 GB     DDR4
180    ASUS           Intel        Core i3            10th   4 GB     DDR4
188    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
107    ASUS           Intel        Core i3            11th   8 GB     DDR4
189    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
112    ASUS           Intel        Core i3            11th   8 GB     DDR4
92     ASUS           Intel        Core i3            11th   8 GB     DDR4
66     ASUS           Intel        Core i3            11th   4 GB     DDR4
156    ASUS           Intel        Core i3            10th   4 GB     DDR4
208    ASUS           Intel        Core i5            11th   8 GB     DDR4
6      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
45     ASUS           Intel        Core i3            11th   8 GB     DDR4
13     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
5      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
70     ASUS           Intel        Core i3            10th   4 GB     DDR4
21     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
14     ASUS           Intel        Core i3            11th   4 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
81     ASUS           Intel        Core i3            11th   4 GB     DDR4
169    ASUS           Intel        Core i3            10th   4 GB     DDR4
83     ASUS           Intel        Core i3            11th   8 GB     DDR4

In [83]:
datos.sort_values(by="Price")  # Ordena por precio en sentido creciente

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
194  Lenovo           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
12    Avita           Intel   Celeron Dual   Not Available   4 GB     DDR4
189    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
188    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
170    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
163    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
6      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
5      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
13     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
84     ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
167    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
64     acer           Intel   Celeron Dual   Not Available   4 GB     DDR4
21     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
153    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
195  Lenovo           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
193  Lenovo           Intel   Celeron Dual   Not Available   4 GB  LPDDR4X
633    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
634    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
190      HP           Intel   Celeron Dual   Not Available   4 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
632    ASUS           Intel   Pentium Quad   Not Available   4 GB   LPDDR4
191      HP           Intel   Celeron Dual   Not Available   4 GB     DDR4
20     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
192  Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
635    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
628    acer           Intel   Pentium Quad   Not Available   4 GB     DDR4
19   Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
17   Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
18       HP           Intel   Celeron Dual   Not Available   8 GB     DDR4
130    ASUS           Intel        Core i3            10th   8 GB     DDR4
658      HP             AMD        Ryzen 3   Not Available   4 GB     DDR4
22       HP           Intel        Core i3             7th   4 GB     DDR4
630    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
165    ASUS           Intel        Core i3            10th   8 GB     DDR4
626      HP           Intel   Pentium Quad   Not Available   8 GB     DDR4
641    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
27     ASUS           Intel        Core i3            10th   8 GB     DDR4
151    ASUS           Intel        Core i3            10th   4 GB     DDR4
627    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
169    ASUS           Intel        Core i3            10th   4 GB     DDR4
24     ASUS           Intel        Core i3            11th   4 GB     DDR4
644    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
139    ASUS           Intel        Core i3            10th   4 GB     DDR4
659  Lenovo             AMD        Ryzen 3   Not Available   4 GB     DDR4
648    acer             AMD        Ryzen 3   Not Available   4 GB     DDR4
148    ASUS           Intel        Core i3            10th   4 GB     DDR4
60     ASUS           Intel        Core i3            10th   4 GB     DDR4
136    ASUS           Intel        Core i3            10th   4 GB     DDR4
131  Lenovo           Intel        Core i3            10th   8 GB     DDR4
89     ASUS           Intel        Core i3            10th   4 GB     DDR4
26     ASUS           Intel        Core i3            11th   4 GB     DDR4
631    DELL           Intel   Pentium Quad   Not Available   4 GB     DDR4
652    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
14     ASUS           Intel        Core i3            11th   4 GB     DDR4
637    ASUS             AMD        Ryzen 3   Not Available   8 GB     DDR4
629    DELL           Intel   Pentium Quad   Not Available   4 GB     DDR4
149      HP           Intel        Core i3            10th   4 GB     DDR4
55   Lenovo           Intel        Core i3            10th   4 GB     DDR4
645    acer             AMD        Ryzen 3   Not Available   8 GB     DDR4
143  Lenovo           Intel        Core i3            10th   4 GB     DDR4
639    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
40     DELL           Intel        Core i3            10th   4 GB     DDR4
42     ASUS           Intel        Core i3            11th   8 GB     DDR4
81     ASUS           Intel        Core i3            11th   4 GB     DDR4
161    acer           Intel        Core i3            11th   4 GB     DDR4
654    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
33     ASUS           Intel        Core i3            11th   8 GB     DDR4
636      HP             AMD        Ryzen 3   Not Available   8 GB     DDR4
25   Lenovo           Intel        Core i3            10th   8 GB     DDR4
86     ASUS           Intel        Core i3            10th   8 GB     DDR4
157    DELL           Intel        Core i3            11th   8 GB     DDR4
35   Lenovo           Intel        Core i3            10th   8 GB     DDR4
32     ASUS           Intel        Core i3            11th   8 GB     DDR4
643    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
156    ASUS           Intel        Core i3            10th   4 GB     DDR4
52     ASUS           Intel        Core i3            11th   8 GB     DDR4
166    ASUS           Intel        Core i3            11th   8 GB     DDR4
115      HP           Intel        Core i3            10th   4 GB     DDR4
140    ASUS           Intel        Core i3            11th   8 GB     DDR4
43   Lenovo           Intel        Core i3            10th   4 GB     DDR4
56   Lenovo           Intel        Core i3            10th   8 GB     DDR4
34   Lenovo           Intel        Core i3            11th   8 GB     DDR4
58      MSI           Intel        Core i3            10th   4 GB     DDR4
53   Lenovo           Intel        Core i3            11th   4 GB     DDR4
31     acer           Intel        Core i3            11th   8 GB     DDR4
150    ASUS           Intel        Core i3            10th   4 GB     DDR4
138  Lenovo           Intel        Core i3            10th   8 GB     DDR4
94   Lenovo           Intel        Core i3            10th   8 GB     DDR4
159  Lenovo           Intel        Core i3            10th   8 GB     DDR4
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4
134    DELL           Intel        Core i3            10th   8 GB     DDR4
653      HP             AMD        Ryzen 3   Not Available   8 GB     DDR4
44     DELL           Intel        Core i3            10th   4 GB     DDR4
29     DELL           Intel        Core i3            10th   8 GB     DDR4
638    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
147      HP           Intel        Core i3            11th   4 GB     DDR4
28       HP           Intel        Core i3            11th   8 GB     DDR4
186    DELL           Intel        Core i3            11th   4 GB     DDR4
79     DELL           Intel        Core i3            10th   4 GB     DDR4
640    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
141    DELL           Intel        Core i3            10th   4 GB     DDR4
66     ASUS           Intel        Core i3            11th   4 GB     DDR4
70     ASUS           Intel        Core i3            10th   4 GB     DDR4
660    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
656    DELL             AMD        Ryzen 3   Not Available   4 GB     DDR4
98     ASUS           Intel        Core i3            10th   4 GB     DDR4
38   Lenovo           Intel        Core i3            11th   8 GB     DDR4
144      HP           Intel        Core i3            11th   4 GB     DDR4
71   Lenovo           Intel        Core i3            11th   4 GB     DDR4
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4
69   Lenovo           Intel        Core i3            10th   4 GB     DDR4
46   Lenovo           Intel        Core i3            10th   8 GB     DDR4
61   Lenovo           Intel        Core i3            10th   4 GB     DDR4
168    DELL           Intel        Core i3            10th   8 GB     DDR4
642    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
650    DELL             AMD        Ryzen 3   Not Available   4 GB     DDR4
154      HP           Intel        Core i3            10th   4 GB     DDR4
142    DELL           Intel        Core i3            10th   4 GB     DDR4
176    acer           Intel        Core i3            11th   8 GB     DDR4
119    ASUS           Intel        Core i3            10th   4 GB     DDR4
62   Lenovo           Intel        Core i3            10th   4 GB     DDR4
101     MSI           Intel        Core i3            10th   8 GB     DDR4
125    ASUS           Intel        Core i3            10th   4 GB     DDR4
180    ASUS           Intel        Core i3            10th   4 GB     DDR4
78   Lenovo           Intel        Core i3            10th   4 GB     DDR4
105      HP           Intel        Core i3            11th   8 GB     DDR4
183    DELL           Intel        Core i3            10th   4 GB     DDR4
164    DELL           Intel        Core i3            11th   8 GB     DDR4
647      HP             AMD        Ryzen 3   Not Available   8 GB     DDR4
122    ASUS           Intel        Core i3            10th   4 GB     DDR4
171    DELL           Intel        Core i3            10th   8 GB     DDR4
49     DELL           Intel        Core i3            11th   8 GB     DDR4
160    ASUS           Intel        Core i3            11th   8 GB     DDR4
126    DELL           Intel        Core i3            10th   4 GB     DDR4
174    ASUS           Intel        Core i3            11th   8 GB     DDR4
36     DELL           Intel        Core i3            11th   8 GB     DDR4
664    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
662    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
68     ASUS           Intel        Core i3            11th   4 GB     DDR4
102    ASUS           Intel        Core i3            11th   8 GB     DDR4
145      HP           Intel        Core i3            11th   4 GB     DDR4
73   Lenovo           Intel        Core i3            10th   4 GB     DDR4
51   Lenovo           Intel        Core i3            11th   8 GB     DDR4
110    DELL           Intel        Core i3            10th   8 GB     DDR4
50     DELL           Intel        Core i3            11th   8 GB     DDR4
67   Lenovo           Intel        Core i3            10th   4 GB     DDR4
661      HP             AMD        Ryzen 3   Not Available   8 GB     DDR4
651    DELL             AMD        Ryzen 3   Not Available   8 GB     DDR4
133    DELL           Intel        Core i3            11th   8 GB     DDR4
39     DELL           Intel        Core i3            11th   8 GB     DDR4
96       HP           Intel        Core i3            10th   8 GB     DDR4
72       HP           Intel        Core i3            11th   4 GB     DDR4
63     DELL           Intel        Core i3            10th   4 GB     DDR4
132    DELL           Intel        Core i3            11th   8 GB     DDR4
162    DELL           Intel        Core i3            11th   8 GB     DDR4
88       HP           Intel        Core i3            11th   8 GB     DDR4
175    DELL           Intel        Core i3            11th   4 GB     DDR4
47     DELL           Intel        Core i3            11th   8 GB     DDR4
90     ASUS           Intel        Core i3            11th   8 GB     DDR4
93     ASUS           Intel        Core i3            11th   8 GB     DDR4
87       HP           Intel        Core i3            11th   8 GB     DDR4
113  Lenovo           Intel        Core i3            11th   8 GB     DDR4
107    ASUS           Intel        Core i3            11th   8 GB     DDR4
120    ASUS           Intel        Core i3            10th   4 GB     DDR4
155    DELL           Intel        Core i3            10th   4 GB     DDR4
152    DELL           Intel        Core i3            10th   4 GB     DDR4
646      HP             AMD        Ryzen 3   Not Available   8 GB     DDR4
182    DELL           Intel        Core i3            11th   4 GB     DDR4
178    DELL           Intel        Core i3            11th   4 GB     DDR4
135      HP           Intel        Core i3            11th   8 GB     DDR4
137    DELL           Intel        Core i3            11th   8 GB     DDR4
76     DELL           Intel        Core i3            11th   4 GB     DDR4
97       HP           Intel        Core i3            11th   8 GB     DDR4
146    DELL           Intel        Core i3            11th   4 GB     DDR4
181    DELL           Intel        Core i3            11th   4 GB     DDR4
657    DELL             AMD        Ryzen 3   Not Available   4 GB     DDR4
676    acer             AMD        Ryzen 5   Not Available   8 GB     DDR4
80   Lenovo           Intel        Core i3            11th   4 GB     DDR4
184    DELL           Intel        Core i3            10th   4 GB     DDR4
75       HP           Intel        Core i3            11th   4 GB     DDR4
667    DELL             AMD        Ryzen 5   Not Available   4 GB     DDR4
59     DELL           Intel        Core i3            11th   4 GB     DDR4
649      HP             AMD        Ryzen 3   Not Available   4 GB     DDR4
665    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
173    DELL           Intel        Core i3            11th   8 GB     DDR4
663    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
438      HP           Intel        Core i5             7th   4 GB     DDR4
179    DELL           Intel        Core i3            10th   4 GB     DDR4
121    ASUS           Intel        Core i3            11th   4 GB     DDR4
57       HP           Intel        Core i3            11th   4 GB     DDR4
106      HP           Intel        Core i3            11th   8 GB     DDR4
394   Avita           Intel        Core i5             8th   8 GB     DDR4
104    ASUS           Intel        Core i3            11th   8 GB     DDR4
707    acer             AMD        Ryzen 5   Not Available   4 GB     DDR4
112    ASUS           Intel        Core i3            11th   8 GB     DDR4
54   Lenovo           Intel        Core i3            11th   4 GB     DDR4
111    DELL           Intel        Core i3            10th   8 GB     DDR4
172    DELL           Intel        Core i3            11th   8 GB     DDR4
114      HP           Intel        Core i3            11th   4 GB     DDR4
109      HP           Intel        Core i3            11th   8 GB     DDR4
128    DELL           Intel        Core i3            11th   8 GB     DDR4
623    ASUS           Intel   Pentium Quad   Not Available   4 GB  LPDDR4X
45     ASUS           Intel        Core i3            11th   8 GB     DDR4
95     DELL           Intel        Core i3            11th   8 GB     DDR4
37     ASUS           Intel        Core i3            11th   8 GB     DDR4
23       HP           Intel        Core i5             7th   4 GB     DDR4
187    DELL           Intel        Core i3            10th   8 GB     DDR4
77     DELL           Intel        Core i3            11th   4 GB     DDR4
437      HP           Intel        Core i5             8th   8 GB     DDR4
420    ASUS           Intel        Core i5            10th   8 GB     DDR4
417    acer           Intel        Core i5            11th   8 GB     DDR4
204  Lenovo           Intel        Core i5            10th   8 GB   LPDDR4
679    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
229    ASUS           Intel        Core i5            10th   8 GB     DDR4
118      HP           Intel        Core i3            11th   4 GB     DDR4
258    ASUS           Intel        Core i5            10th   8 GB     DDR4
672     MSI             AMD        Ryzen 5   Not Available   8 GB     DDR4
230  Lenovo           Intel        Core i5            10th   8 GB     DDR4
74     ASUS           Intel        Core i3            11th   4 GB     DDR4
82     DELL           Intel        Core i3            11th   8 GB     DDR4
440      HP           Intel        Core i5            10th   8 GB     DDR4
124      HP           Intel        Core i3            11th   4 GB     DDR4
83     ASUS           Intel        Core i3            11th   8 GB     DDR4
177    DELL           Intel        Core i3            11th   8 GB     DDR4
670  Lenovo             AMD        Ryzen 5   Not Available   8 GB     DDR4
673      HP             AMD        Ryzen 5   Not Available   8 GB     DDR4
99      MSI           Intel        Core i3            11th   8 GB     DDR4
418    DELL           Intel        Core i5            11th   8 GB     DDR4
92     ASUS           Intel        Core i3            11th   8 GB     DDR4
685      HP             AMD        Ryzen 5   Not Available   8 GB     DDR4
208    ASUS           Intel        Core i5            11th   8 GB     DDR4
185    DELL           Intel        Core i3            11th   4 GB     DDR4
158      HP           Intel        Core i3             7th   8 GB     DDR4
729    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
206  Lenovo           Intel        Core i5            11th   8 GB     DDR4
213    ASUS           Intel        Core i5            11th   8 GB     DDR4
694    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
671      HP             AMD        Ryzen 5   Not Available   8 GB     DDR4
416    acer           Intel        Core i5            11th   8 GB     DDR4
227  Lenovo           Intel        Core i5            10th   8 GB     DDR4
695    DELL             AMD        Ryzen 5   Not Available   8 GB     DDR4
48     DELL           Intel        Core i3            11th   8 GB     DDR4
250    ASUS           Intel        Core i5            10th   8 GB     DDR4
714    acer             AMD        Ryzen 5   Not Available   4 GB     DDR4
716    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
712    acer             AMD        Ryzen 5   Not Available   4 GB     DDR4
666     MSI             AMD        Ryzen 5   Not Available   4 GB     DDR4
462    ASUS           Intel        Core i5            11th   8 GB     DDR4
8    Lenovo           Intel        Core i5            10th   4 GB     DDR4
123      HP           Intel        Core i3            11th   4 GB     DDR4
196    acer           Intel        Core i5   Not Available   8 GB     DDR5
442    ASUS           Intel        Core i5            11th   8 GB     DDR4
117    ASUS           Intel        Core i3            11th   4 GB     DDR4
722      HP             AMD        Ryzen 5   Not Available   8 GB     DDR4
91     ASUS           Intel        Core i3            11th   8 GB  LPDDR4X
222  Lenovo           Intel        Core i5            11th   8 GB     DDR4
736    DELL             AMD        Ryzen 5   Not Available   4 GB     DDR4
713      HP             AMD        Ryzen 5   Not Available   4 GB     DDR4
423  Lenovo           Intel        Core i5             4th   8 GB     DDR3
715      HP             AMD        Ryzen 5   Not Available   4 GB     DDR4
655    DELL             AMD        Ryzen 3   Not Available   4 GB     DDR4
675  Lenovo             AMD        Ryzen 5   Not Available   8 GB     DDR4
221  Lenovo           Intel        Core i5            11th   8 GB     DDR4
738      HP             AMD        Ryzen 5   Not Available   4 GB     DDR4

In [84]:
datos.sort_values(by="Price", ascending=False)  # Ordena por precio en sentido decreciente

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
594    ASUS           Intel        Core i9            11th  16 GB     DDR4
621   APPLE              M1             M1            10th  32 GB     DDR4
590    ASUS           Intel        Core i9            12th  16 GB     DDR5
433     MSI           Intel        Core i5            10th   8 GB   LPDDR4
547     MSI           Intel        Core i7            12th  16 GB     DDR5
591    ASUS           Intel        Core i9            10th  16 GB     DDR4
593  Lenovo           Intel        Core i9            10th  16 GB     DDR4
523  Lenovo           Intel        Core i7             8th  16 GB     DDR4
620   APPLE              M1             M1            10th  16 GB     DDR4
507      HP           Intel        Core i7            10th  16 GB   LPDDR3
574  Lenovo           Intel        Core i7            10th  16 GB     DDR4
817    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
557    ASUS           Intel        Core i7            10th  16 GB     DDR4
576    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
563  Lenovo           Intel        Core i7             9th  16 GB     DDR4
614   APPLE              M1             M1            10th  16 GB     DDR4
622   APPLE              M1             M1            10th  16 GB     DDR4
619   APPLE              M1             M1            10th  16 GB     DDR4
546    ASUS           Intel        Core i7            10th  16 GB     DDR4
528  Lenovo           Intel        Core i7            10th  16 GB   LPDDR3
477     MSI           Intel        Core i5            10th   8 GB   LPDDR4
798    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
540    ASUS           Intel        Core i7            11th  16 GB     DDR4
589     MSI           Intel        Core i9            11th  16 GB     DDR4
613   APPLE              M1             M1            10th  16 GB     DDR4
543      HP           Intel        Core i7            10th  16 GB     DDR4
407   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
435     MSI           Intel        Core i5            10th   8 GB   LPDDR4
408   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
516  Lenovo           Intel        Core i7            10th  16 GB     DDR4
310   APPLE           Intel        Core i5             8th   8 GB     DDR3
555      HP           Intel        Core i7            11th  16 GB     DDR4
618   APPLE              M1             M1            10th  16 GB     DDR4
587    acer           Intel        Core i9            11th  32 GB     DDR4
568    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
566    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
569      HP           Intel        Core i7            11th  16 GB  LPDDR4X
513      HP           Intel        Core i7            10th  16 GB     DDR4
813    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
526  Lenovo           Intel        Core i7            10th  16 GB     DDR4
517  Lenovo           Intel        Core i7            10th  16 GB     DDR4
583     MSI           Intel        Core i7            10th  16 GB     DDR4
782      HP             AMD        Ryzen 7   Not Available   4 GB     DDR4
309   APPLE           Intel        Core i5            10th   8 GB  LPDDR4X
575    acer           Intel        Core i7            10th  16 GB     DDR4
562    ASUS           Intel        Core i7            11th  16 GB     DDR4
414  Lenovo           Intel        Core i5            10th   8 GB     DDR4
544     MSI           Intel        Core i7            11th  16 GB     DDR4
565    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
797    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
550  Lenovo           Intel        Core i7            11th  16 GB     DDR4
552      HP           Intel        Core i7            11th  16 GB  LPDDR4X
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
606   APPLE              M1             M1            10th  16 GB     DDR4
370     MSI           Intel        Core i5             8th   8 GB     DDR5
617   APPLE              M1             M1            10th   8 GB     DDR4
313  Lenovo           Intel        Core i5            10th   8 GB     DDR4
802     MSI             AMD        Ryzen 9   Not Available   4 GB     DDR4
598    ASUS           Intel        Core i7            10th  16 GB  LPDDR4X
434     MSI           Intel        Core i5            10th   8 GB   LPDDR4
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
537      HP           Intel        Core i7            10th  16 GB     DDR4
809    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
812    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
807      HP             AMD        Ryzen 9   Not Available   4 GB     DDR4
553     MSI           Intel        Core i7            12th  16 GB     DDR4
588    acer           Intel        Core i9            11th  16 GB     DDR4
592    ASUS           Intel        Core i9            11th  16 GB     DDR4
201    DELL           Intel        Core i5            10th   8 GB   LPDDR4
816    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
573      HP           Intel        Core i7            11th  16 GB     DDR4
211      HP           Intel        Core i5             8th   8 GB     DDR4
796    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
514    DELL           Intel        Core i7            11th  16 GB  LPDDR4X
535    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
806    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
603   APPLE              M1             M1            10th  16 GB     DDR4
386    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
611   APPLE              M1             M1            10th   8 GB     DDR4
564    ASUS           Intel        Core i7            11th  16 GB     DDR4
784  Lenovo             AMD        Ryzen 7   Not Available   4 GB     DDR4
814    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
369      HP           Intel        Core i5            11th   8 GB  LPDDR4X
551     MSI           Intel        Core i7            11th  16 GB     DDR4
808    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
800    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
554    acer           Intel        Core i7            11th  16 GB     DDR4
612   APPLE              M1             M1            10th  16 GB     DDR4
558      HP           Intel        Core i7            11th  16 GB  LPDDR4X
361      HP           Intel        Core i5            10th   8 GB     DDR4
607   APPLE              M1             M1            10th   8 GB     DDR4
415  Lenovo           Intel        Core i5            10th   8 GB     DDR4
805    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
615   APPLE              M1             M1            10th   4 GB     DDR4
541    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
811    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
545  Lenovo           Intel        Core i7            11th  16 GB  LPDDR4X
542    DELL           Intel        Core i7            11th  16 GB     DDR4
810    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
548      HP           Intel        Core i7            11th  16 GB     DDR4
509    DELL           Intel        Core i7             8th  16 GB     DDR3
561    ASUS           Intel        Core i7            11th  16 GB     DDR4
582    acer           Intel        Core i7            10th  16 GB     DDR4
586    acer           Intel        Core i7            11th  16 GB     DDR4
567  Lenovo           Intel        Core i7            10th  16 GB  LPDDR4X
197    acer           Intel        Core i5   Not Available   8 GB   LPDDR4
539     MSI           Intel        Core i7            11th  16 GB     DDR4
560    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
527      HP           Intel        Core i7            11th  16 GB     DDR4
815    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
549      HP           Intel        Core i7            11th  16 GB     DDR4
578      HP           Intel        Core i7             8th  16 GB     DDR4
363      HP           Intel        Core i5            11th   8 GB     DDR4
779    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
333      HP           Intel        Core i5            10th   8 GB     DDR4
804    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
307    DELL           Intel        Core i5            11th   8 GB  LPDDR4X
368    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
801    ASUS             AMD        Ryzen 9   Not Available  16 GB  LPDDR4X
799    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
336  Lenovo           Intel        Core i5            10th   8 GB     DDR4
778    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
600   APPLE              M1             M1            10th   8 GB     DDR4
786    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
602   APPLE              M1             M1            10th   8 GB     DDR4
322      HP           Intel        Core i5            11th   8 GB  LPDDR4X
762    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
297    DELL           Intel        Core i5            10th   8 GB  LPDDR4X
790    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
529  Lenovo           Intel        Core i7            11th  16 GB     DDR4
365    acer           Intel        Core i5            11th   8 GB     DDR4
521    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
504     MSI           Intel        Core i7            10th  16 GB     DDR4
596     MSI           Intel        Core i5            10th   8 GB   LPDDR4
597     MSI           Intel        Core i5            10th   8 GB   LPDDR4
518    DELL           Intel        Core i7            10th  16 GB     DDR4
763      HP             AMD        Ryzen 7   Not Available   4 GB     DDR4
748    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
767  Lenovo             AMD        Ryzen 7   Not Available   4 GB     DDR4
316      HP           Intel        Core i5            10th   8 GB     DDR4
199    ASUS           Intel        Core i5            10th   8 GB   LPDDR4
291    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
381    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
803    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
616   APPLE              M1             M1            10th   8 GB     DDR4
520     MSI           Intel        Core i7            10th  16 GB     DDR4
610   APPLE              M1             M1            10th   8 GB     DDR4
534    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
601   APPLE              M1             M1            10th  16 GB     DDR4
604   APPLE              M1             M1            10th  16 GB     DDR4
500      HP           Intel        Core i7            11th  16 GB     DDR4
608   APPLE              M1             M1            10th   8 GB     DDR4
497      HP           Intel        Core i7            11th  16 GB     DDR4
559  Lenovo           Intel        Core i7            11th  16 GB     DDR4
203      HP           Intel        Core i5            10th   8 GB   LPDDR4
609   APPLE              M1             M1            10th   8 GB     DDR4
400      HP           Intel        Core i5            11th  16 GB     DDR4
519      HP           Intel        Core i7            11th  16 GB     DDR4
522    ASUS           Intel        Core i7             8th  16 GB     DDR3
538    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
785    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
774     MSI             AMD        Ryzen 7   Not Available  16 GB     DDR4
490  Lenovo           Intel        Core i7            11th  16 GB     DDR4
339    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
498    DELL           Intel        Core i7            11th  16 GB     DDR4
530    DELL           Intel        Core i7            11th  16 GB     DDR4
351    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
375    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
744  Lenovo             AMD        Ryzen 7   Not Available  16 GB     DDR4
789    ASUS             AMD        Ryzen 7   Not Available   4 GB  LPDDR4X
780    acer             AMD        Ryzen 7   Not Available   4 GB     DDR4
325    acer           Intel        Core i5             8th   8 GB     DDR4
536    ASUS           Intel        Core i7            11th  16 GB     DDR4
710    DELL             AMD        Ryzen 5   Not Available   4 GB     DDR4
584    ASUS           Intel        Core i7             8th  16 GB     DDR4
692      HP             AMD        Ryzen 5   Not Available  16 GB     DDR4
252      HP           Intel        Core i5            11th   8 GB  LPDDR4X
781    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
494    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
499    ASUS           Intel        Core i7            11th  16 GB     DDR4
511     MSI           Intel        Core i7            11th  16 GB     DDR4
524    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
572      HP           Intel        Core i7            11th  16 GB     DDR4
198    acer           Intel        Core i5            10th   8 GB   LPDDR4
376      HP           Intel        Core i5            11th   8 GB     DDR4
577    ASUS           Intel        Core i7            10th  16 GB     DDR4
746    DELL             AMD        Ryzen 7   Not Available  16 GB     DDR4
556    DELL           Intel        Core i7            11th  16 GB     DDR4
10     acer             AMD        Ryzen 5            10th   4 GB     DDR4
493      HP           Intel        Core i7            11th  16 GB     DDR4
749    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
776      HP             AMD        Ryzen 7   Not Available  16 GB     DDR4
585    acer           Intel        Core i7            11th  16 GB     DDR4
512      HP           Intel        Core i7            11th  16 GB     DDR4
384  Lenovo           Intel        Core i5            11th   8 GB     DDR4
705    ASUS             AMD        Ryzen 5   Not Available   4 GB  LPDDR4X
755      HP             AMD        Ryzen 7   Not Available   4 GB     DDR4
502      HP           Intel        Core i7            11th  16 GB     DDR4
350  Lenovo           Intel        Core i5            11th   8 GB     DDR4
506     MSI           Intel        Core i7            11th  16 GB  LPDDR4X
233    ASUS           Intel        Core i5            11th  16 GB     DDR4
793    acer             AMD        Ryzen 7   Not Available  16 GB     DDR4
764    DELL             AMD        Ryzen 7   Not Available   4 GB     DDR4
272    DELL           Intel        Core i5            11th  16 GB     DDR4
769    DELL             AMD        Ryzen 7   Not Available   4 GB     DDR4
268    DELL           Intel        Core i5            11th  16 GB     DDR4
335    DELL           Intel        Core i5            11th   8 GB     DDR4
362    ASUS           Intel        Core i5            11th   8 GB     DDR4
503  Lenovo           Intel        Core i7            11th  16 GB     DDR4
478    DELL           Intel        Core i7             8th  16 GB     DDR4
410    ASUS           Intel        Core i5            11th   8 GB     DDR4
286  Lenovo           Intel        Core i5            11th   8 GB     DDR4
396  Lenovo           Intel        Core i5            10th   8 GB     DDR4
505     MSI           Intel        Core i7            11th  16 GB     DDR4
595     MSI           Intel        Core i5            10th   8 GB   LPDDR4
380    ASUS           Intel        Core i5            10th   8 GB     DDR4
207    acer           Intel        Core i5             7th   8 GB     DDR3
525  Lenovo           Intel        Core i7             8th  16 GB     DDR4
489  Lenovo           Intel        Core i7            11th  16 GB     DDR4
571  Lenovo           Intel        Core i7            11th  16 GB   LPDDR4
510    ASUS           Intel        Core i7             8th  16 GB   LPDDR3
599   APPLE              M1             M1            10th   8 GB     DDR4
379    ASUS           Intel        Core i5             8th   8 GB     DDR4
605   APPLE              M1             M1            10th   8 GB     DDR4
295    ASUS           Intel        Core i5            11th   8 GB     DDR4
283    ASUS           Intel        Core i5            11th   8 GB     DDR4
382    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
349    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
395    ASUS           Intel        Core i5            11th   8 GB     DDR4
495  Lenovo           Intel        Core i7            11th  16 GB     DDR4
352    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
773      HP             AMD        Ryzen 7   Not Available  16 GB     DDR4
359    ASUS           Intel        Core i5            11th   8 GB   LPDDR4
533     MSI           Intel        Core i7            10th  16 GB     DDR4
754  Lenovo             AMD        Ryzen 7   Not Available   4 GB     DDR4
791    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
411    ASUS           Intel        Core i5            11th   8 GB     DDR4
706      HP             AMD        Ryzen 5   Not Available   4 GB     DDR4
777      HP             AMD        Ryzen 7   Not Available  16 GB     DDR4
403  Lenovo           Intel        Core i5            11th   8 GB     DDR4
432    ASUS           Intel        Core i5            10th   8 GB     DDR4
747    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
373    DELL           Intel        Core i5            10th   8 GB     DDR4
366  Lenovo           Intel        Core i5            11th   8 GB     DDR4
364    DELL           Intel        Core i5            11th   8 GB     DDR4
377    DELL           Intel        Core i5            11th   8 GB     DDR4
247    ASUS           Intel        Core i5            11th  16 GB     DDR4
409    ASUS           Intel        Core i5            10th   8 GB     DDR4
581    ASUS           Intel        Core i7            11th  16 GB     DDR4
348      HP           Intel        Core i5            11th   8 GB     DDR4
210    acer           Intel        Core i5             8th   8 GB     DDR3
794    acer             AMD        Ryzen 7   Not Available  16 GB     DDR4
531    ASUS           Intel        Core i7             8th   8 GB   LPDDR3
429    ASUS           Intel        Core i5             8th   8 GB     DDR4
727  Lenovo             AMD        Ryzen 5   Not Available   4 GB  LPDDR4X
750  Lenovo           Intel        Ryzen 7   Not Available   4 GB     DDR4
718    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
795  Lenovo             AMD        Ryzen 7   Not Available   4 GB     DDR4
735      HP             AMD        Ryzen 5   Not Available   4 GB     DDR4
772      HP             AMD        Ryzen 7   Not Available  16 GB     DDR4
276    DELL           Intel        Core i5            11th   8 GB     DDR4
292     MSI           Intel        Core i5            11th   8 GB  LPDDR4X
492  Lenovo           Intel        Core i7            11th   8 GB     DDR4

In [86]:
# Para ordenar el DataFrame utilizando varios criterios
# Ordenar por marca y luego por precio

datos.sort_values(by=["brand", "rating","Price"])

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
599   APPLE              M1             M1            10th   8 GB     DDR4
605   APPLE              M1             M1            10th   8 GB     DDR4
609   APPLE              M1             M1            10th   8 GB     DDR4
608   APPLE              M1             M1            10th   8 GB     DDR4
601   APPLE              M1             M1            10th  16 GB     DDR4
604   APPLE              M1             M1            10th  16 GB     DDR4
610   APPLE              M1             M1            10th   8 GB     DDR4
616   APPLE              M1             M1            10th   8 GB     DDR4
600   APPLE              M1             M1            10th   8 GB     DDR4
602   APPLE              M1             M1            10th   8 GB     DDR4
615   APPLE              M1             M1            10th   4 GB     DDR4
607   APPLE              M1             M1            10th   8 GB     DDR4
612   APPLE              M1             M1            10th  16 GB     DDR4
611   APPLE              M1             M1            10th   8 GB     DDR4
603   APPLE              M1             M1            10th  16 GB     DDR4
606   APPLE              M1             M1            10th  16 GB     DDR4
617   APPLE              M1             M1            10th   8 GB     DDR4
309   APPLE           Intel        Core i5            10th   8 GB  LPDDR4X
618   APPLE              M1             M1            10th  16 GB     DDR4
310   APPLE           Intel        Core i5             8th   8 GB     DDR3
407   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
408   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
613   APPLE              M1             M1            10th  16 GB     DDR4
614   APPLE              M1             M1            10th  16 GB     DDR4
619   APPLE              M1             M1            10th  16 GB     DDR4
622   APPLE              M1             M1            10th  16 GB     DDR4
620   APPLE              M1             M1            10th  16 GB     DDR4
621   APPLE              M1             M1            10th  32 GB     DDR4
165    ASUS           Intel        Core i3            10th   8 GB     DDR4
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
723    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
189    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
188    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
170    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
163    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
6      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
5      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
13     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
21     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
633    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
634    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
632    ASUS           Intel   Pentium Quad   Not Available   4 GB   LPDDR4
635    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
130    ASUS           Intel        Core i3            10th   8 GB     DDR4
151    ASUS           Intel        Core i3            10th   4 GB     DDR4
169    ASUS           Intel        Core i3            10th   4 GB     DDR4
139    ASUS           Intel        Core i3            10th   4 GB     DDR4
148    ASUS           Intel        Core i3            10th   4 GB     DDR4
14     ASUS           Intel        Core i3            11th   4 GB     DDR4
60     ASUS           Intel        Core i3            10th   4 GB     DDR4
136    ASUS           Intel        Core i3            10th   4 GB     DDR4
52     ASUS           Intel        Core i3            11th   8 GB     DDR4
166    ASUS           Intel        Core i3            11th   8 GB     DDR4
140    ASUS           Intel        Core i3            11th   8 GB     DDR4
70     ASUS           Intel        Core i3            10th   4 GB     DDR4
180    ASUS           Intel        Core i3            10th   4 GB     DDR4
160    ASUS           Intel        Core i3            11th   8 GB     DDR4
68     ASUS           Intel        Core i3            11th   4 GB     DDR4
102    ASUS           Intel        Core i3            11th   8 GB     DDR4
121    ASUS           Intel        Core i3            11th   4 GB     DDR4
112    ASUS           Intel        Core i3            11th   8 GB     DDR4
623    ASUS           Intel   Pentium Quad   Not Available   4 GB  LPDDR4X
74     ASUS           Intel        Core i3            11th   4 GB     DDR4
83     ASUS           Intel        Core i3            11th   8 GB     DDR4
208    ASUS           Intel        Core i5            11th   8 GB     DDR4
213    ASUS           Intel        Core i5            11th   8 GB     DDR4
462    ASUS           Intel        Core i5            11th   8 GB     DDR4
117    ASUS           Intel        Core i3            11th   4 GB     DDR4
445    ASUS           Intel        Core i5            11th   8 GB     DDR4
427    ASUS           Intel        Core i5            10th   8 GB     DDR4
751    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
329    ASUS           Intel        Core i5            11th   8 GB     DDR4
624    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
7      ASUS           Intel        Core i5            10th   8 GB     DDR4
274    ASUS           Intel        Core i5            11th  16 GB     DDR4
263    ASUS           Intel        Core i5            11th  16 GB     DDR4
265    ASUS           Intel        Core i5            11th  16 GB     DDR4
278    ASUS           Intel        Core i5            11th  16 GB     DDR4
430    ASUS           Intel        Core i5            10th   8 GB     DDR4
625    ASUS           Intel   Pentium Quad   Not Available   8 GB  LPDDR4X
261    ASUS           Intel        Core i5            10th   8 GB     DDR4
466    ASUS           Intel        Core i5            11th   8 GB     DDR4
239    ASUS           Intel        Core i5            11th  16 GB     DDR4
3      ASUS           Intel        Core i5            10th   8 GB     DDR4
759    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
269    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
739    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
392    ASUS           Intel        Core i5            11th   8 GB     DDR4
783    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
741    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
745    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
768    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
718    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
429    ASUS           Intel        Core i5             8th   8 GB     DDR4
581    ASUS           Intel        Core i7            11th  16 GB     DDR4
432    ASUS           Intel        Core i5            10th   8 GB     DDR4
791    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
349    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
352    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
359    ASUS           Intel        Core i5            11th   8 GB   LPDDR4
382    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
395    ASUS           Intel        Core i5            11th   8 GB     DDR4
379    ASUS           Intel        Core i5             8th   8 GB     DDR4
380    ASUS           Intel        Core i5            10th   8 GB     DDR4
410    ASUS           Intel        Core i5            11th   8 GB     DDR4
362    ASUS           Intel        Core i5            11th   8 GB     DDR4
705    ASUS             AMD        Ryzen 5   Not Available   4 GB  LPDDR4X
577    ASUS           Intel        Core i7            10th  16 GB     DDR4
494    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
524    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
584    ASUS           Intel        Core i7             8th  16 GB     DDR4
351    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
375    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
538    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
785    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
534    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
748    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
521    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
790    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
762    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
778    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
786    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
368    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
779    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
815    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
561    ASUS           Intel        Core i7            11th  16 GB     DDR4
810    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
808    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
814    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
564    ASUS           Intel        Core i7            11th  16 GB     DDR4
386    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
535    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
806    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
796    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
816    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
592    ASUS           Intel        Core i9            11th  16 GB     DDR4
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
598    ASUS           Intel        Core i7            10th  16 GB  LPDDR4X
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
813    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
566    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
568    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
540    ASUS           Intel        Core i7            11th  16 GB     DDR4
576    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
557    ASUS           Intel        Core i7            10th  16 GB     DDR4
817    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
590    ASUS           Intel        Core i9            12th  16 GB     DDR5
84     ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
167    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
153    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
20     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
630    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
641    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
27     ASUS           Intel        Core i3            10th   8 GB     DDR4
627    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
24     ASUS           Intel        Core i3            11th   4 GB     DDR4
644    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
26     ASUS           Intel        Core i3            11th   4 GB     DDR4
89     ASUS           Intel        Core i3            10th   4 GB     DDR4
637    ASUS             AMD        Ryzen 3   Not Available   8 GB     DDR4
42     ASUS           Intel        Core i3            11th   8 GB     DDR4
81     ASUS           Intel        Core i3            11th   4 GB     DDR4
33     ASUS           Intel        Core i3            11th   8 GB     DDR4
32     ASUS           Intel        Core i3            11th   8 GB     DDR4
86     ASUS           Intel        Core i3            10th   8 GB     DDR4
643    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
156    ASUS           Intel        Core i3            10th   4 GB     DDR4
150    ASUS           Intel        Core i3            10th   4 GB     DDR4
66     ASUS           Intel        Core i3            11th   4 GB     DDR4
98     ASUS           Intel        Core i3            10th   4 GB     DDR4
119    ASUS           Intel        Core i3            10th   4 GB     DDR4
125    ASUS           Intel        Core i3            10th   4 GB     DDR4
122    ASUS           Intel        Core i3            10th   4 GB     DDR4
174    ASUS           Intel        Core i3            11th   8 GB     DDR4
90     ASUS           Intel        Core i3            11th   8 GB     DDR4
93     ASUS           Intel        Core i3            11th   8 GB     DDR4
107    ASUS           Intel        Core i3            11th   8 GB     DDR4
120    ASUS           Intel        Core i3            10th   4 GB     DDR4
104    ASUS           Intel        Core i3            11th   8 GB     DDR4
37     ASUS           Intel        Core i3            11th   8 GB     DDR4
45     ASUS           Intel        Core i3            11th   8 GB     DDR4
420    ASUS           Intel        Core i5            10th   8 GB     DDR4
229    ASUS           Intel        Core i5            10th   8 GB     DDR4
258    ASUS           Intel        Core i5            10th   8 GB     DDR4
92     ASUS           Intel        Core i3            11th   8 GB     DDR4
694    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
250    ASUS           Intel        Core i5            10th   8 GB     DDR4
716    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
442    ASUS           Intel        Core i5            11th   8 GB     DDR4
91     ASUS           Intel        Core i3            11th   8 GB  LPDDR4X
345    ASUS           Intel        Core i5            11th   8 GB     DDR4
305    ASUS           Intel        Core i5            11th   8 GB     DDR4
343    ASUS           Intel        Core i5             8th   8 GB     DDR4
453    ASUS           Intel        Core i5             9th   8 GB     DDR4
253    ASUS           Intel        Core i5             9th   8 GB     DDR4
730    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
732    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
733    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
443    ASUS           Intel        Core i5            10th   8 GB     DDR4
689    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
219    ASUS           Intel        Core i5            10th   8 GB     DDR4
485    ASUS           Intel        Core i7            10th  16 GB     DDR4
457    ASUS           Intel        Core i5            11th  16 GB     DDR4
687    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
701    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
246    ASUS           Intel        Core i5            11th  16 GB     DDR4
452    ASUS           Intel        Core i5            11th   8 GB     DDR4
486    ASUS           Intel        Core i7            10th   8 GB     DDR4
686    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
737    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
224    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
756    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
320    ASUS           Intel        Core i5            10th   8 GB     DDR4
450    ASUS           Intel        Core i5            11th  16 GB     DDR4
456    ASUS           Intel        Core i5            11th  16 GB     DDR4
235    ASUS           Intel        Core i5            10th   8 GB     DDR4
580    ASUS           Intel        Core i7            10th  16 GB     DDR4
228    ASUS           Intel        Core i5            11th   8 GB     DDR4
742    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
743    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
231    ASUS           Intel        Core i5            11th   8 GB     DDR4
299    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
327    ASUS           Intel        Core i5             8th   8 GB   LPDDR3
775    ASUS             AMD        Ryzen 7   Not Available   8 GB  LPDDR4X
241    ASUS           Intel        Core i5            11th  16 GB     DDR4
337    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
402    ASUS           Intel        Core i5            10th   8 GB     DDR4
404    ASUS           Intel        Core i5            11th   8 GB     DDR4
740    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
405    ASUS           Intel        Core i5            11th   8 GB     DDR4
406    ASUS           Intel        Core i5            10th   8 GB     DDR4
491    ASUS           Intel        Core i7            11th   8 GB     DDR4
508    ASUS           Intel        Core i7            11th  16 GB     DDR4
302    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
531    ASUS           Intel        Core i7             8th   8 GB   LPDDR3
247    ASUS           Intel        Core i5            11th  16 GB     DDR4
409    ASUS           Intel        Core i5            10th   8 GB     DDR4
747    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
411    ASUS           Intel        Core i5            11th   8 GB     DDR4
295    ASUS           Intel        Core i5            11th   8 GB     DDR4
510    ASUS           Intel        Core i7             8th  16 GB   LPDDR3
233    ASUS           Intel        Core i5            11th  16 GB     DDR4
749    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
499    ASUS           Intel        Core i7            11th  16 GB     DDR4
781    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
536    ASUS           Intel        Core i7            11th  16 GB     DDR4
339    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
522    ASUS           Intel        Core i7             8th  16 GB     DDR3
789    ASUS             AMD        Ryzen 7   Not Available   4 GB  LPDDR4X
803    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
291    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
199    ASUS           Intel        Core i5            10th   8 GB   LPDDR4
799    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
801    ASUS             AMD        Ryzen 9   Not Available  16 GB  LPDDR4X
804    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
560    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
541    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
811    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
800    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
812    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
809    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
797    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4

In [89]:
datos  # Observamos que la ordenación del dataframe sigue siendo la misma, es decir
       # nos mostró una copia del dataframe ordenado.

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
1    Lenovo           Intel        Core i3            10th   4 GB     DDR4
2    Lenovo           Intel        Core i3            10th   4 GB     DDR4
3      ASUS           Intel        Core i5            10th   8 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
5      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
6      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
7      ASUS           Intel        Core i5            10th   8 GB     DDR4
8    Lenovo           Intel        Core i5            10th   4 GB     DDR4
9      acer             AMD        Ryzen 5            10th   4 GB     DDR4
10     acer             AMD        Ryzen 5            10th   4 GB     DDR4
11     acer             AMD        Ryzen 5            10th   4 GB     DDR4
12    Avita           Intel   Celeron Dual   Not Available   4 GB     DDR4
13     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
14     ASUS           Intel        Core i3            11th   4 GB     DDR4
15       HP           Intel        Core i3            11th   8 GB     DDR4
16       HP           Intel        Core i5            11th   8 GB     DDR4
17   Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
18       HP           Intel   Celeron Dual   Not Available   8 GB     DDR4
19   Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
20     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
21     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
22       HP           Intel        Core i3             7th   4 GB     DDR4
23       HP           Intel        Core i5             7th   4 GB     DDR4
24     ASUS           Intel        Core i3            11th   4 GB     DDR4
25   Lenovo           Intel        Core i3            10th   8 GB     DDR4
26     ASUS           Intel        Core i3            11th   4 GB     DDR4
27     ASUS           Intel        Core i3            10th   8 GB     DDR4
28       HP           Intel        Core i3            11th   8 GB     DDR4
29     DELL           Intel        Core i3            10th   8 GB     DDR4
30       HP           Intel        Core i3            11th   8 GB     DDR4
31     acer           Intel        Core i3            11th   8 GB     DDR4
32     ASUS           Intel        Core i3            11th   8 GB     DDR4
33     ASUS           Intel        Core i3            11th   8 GB     DDR4
34   Lenovo           Intel        Core i3            11th   8 GB     DDR4
35   Lenovo           Intel        Core i3            10th   8 GB     DDR4
36     DELL           Intel        Core i3            11th   8 GB     DDR4
37     ASUS           Intel        Core i3            11th   8 GB     DDR4
38   Lenovo           Intel        Core i3            11th   8 GB     DDR4
39     DELL           Intel        Core i3            11th   8 GB     DDR4
40     DELL           Intel        Core i3            10th   4 GB     DDR4
41   Lenovo           Intel        Core i3            11th   8 GB     DDR4
42     ASUS           Intel        Core i3            11th   8 GB     DDR4
43   Lenovo           Intel        Core i3            10th   4 GB     DDR4
44     DELL           Intel        Core i3            10th   4 GB     DDR4
45     ASUS           Intel        Core i3            11th   8 GB     DDR4
46   Lenovo           Intel        Core i3            10th   8 GB     DDR4
47     DELL           Intel        Core i3            11th   8 GB     DDR4
48     DELL           Intel        Core i3            11th   8 GB     DDR4
49     DELL           Intel        Core i3            11th   8 GB     DDR4
50     DELL           Intel        Core i3            11th   8 GB     DDR4
51   Lenovo           Intel        Core i3            11th   8 GB     DDR4
52     ASUS           Intel        Core i3            11th   8 GB     DDR4
53   Lenovo           Intel        Core i3            11th   4 GB     DDR4
54   Lenovo           Intel        Core i3            11th   4 GB     DDR4
55   Lenovo           Intel        Core i3            10th   4 GB     DDR4
56   Lenovo           Intel        Core i3            10th   8 GB     DDR4
57       HP           Intel        Core i3            11th   4 GB     DDR4
58      MSI           Intel        Core i3            10th   4 GB     DDR4
59     DELL           Intel        Core i3            11th   4 GB     DDR4
60     ASUS           Intel        Core i3            10th   4 GB     DDR4
61   Lenovo           Intel        Core i3            10th   4 GB     DDR4
62   Lenovo           Intel        Core i3            10th   4 GB     DDR4
63     DELL           Intel        Core i3            10th   4 GB     DDR4
64     acer           Intel   Celeron Dual   Not Available   4 GB     DDR4
65     DELL           Intel        Core i3            11th   4 GB     DDR4
66     ASUS           Intel        Core i3            11th   4 GB     DDR4
67   Lenovo           Intel        Core i3            10th   4 GB     DDR4
68     ASUS           Intel        Core i3            11th   4 GB     DDR4
69   Lenovo           Intel        Core i3            10th   4 GB     DDR4
70     ASUS           Intel        Core i3            10th   4 GB     DDR4
71   Lenovo           Intel        Core i3            11th   4 GB     DDR4
72       HP           Intel        Core i3            11th   4 GB     DDR4
73   Lenovo           Intel        Core i3            10th   4 GB     DDR4
74     ASUS           Intel        Core i3            11th   4 GB     DDR4
75       HP           Intel        Core i3            11th   4 GB     DDR4
76     DELL           Intel        Core i3            11th   4 GB     DDR4
77     DELL           Intel        Core i3            11th   4 GB     DDR4
78   Lenovo           Intel        Core i3            10th   4 GB     DDR4
79     DELL           Intel        Core i3            10th   4 GB     DDR4
80   Lenovo           Intel        Core i3            11th   4 GB     DDR4
81     ASUS           Intel        Core i3            11th   4 GB     DDR4
82     DELL           Intel        Core i3            11th   8 GB     DDR4
83     ASUS           Intel        Core i3            11th   8 GB     DDR4
84     ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
85       HP           Intel        Core i3             8th   4 GB     DDR4
86     ASUS           Intel        Core i3            10th   8 GB     DDR4
87       HP           Intel        Core i3            11th   8 GB     DDR4
88       HP           Intel        Core i3            11th   8 GB     DDR4
89     ASUS           Intel        Core i3            10th   4 GB     DDR4
90     ASUS           Intel        Core i3            11th   8 GB     DDR4
91     ASUS           Intel        Core i3            11th   8 GB  LPDDR4X
92     ASUS           Intel        Core i3            11th   8 GB     DDR4
93     ASUS           Intel        Core i3            11th   8 GB     DDR4
94   Lenovo           Intel        Core i3            10th   8 GB     DDR4
95     DELL           Intel        Core i3            11th   8 GB     DDR4
96       HP           Intel        Core i3            10th   8 GB     DDR4
97       HP           Intel        Core i3            11th   8 GB     DDR4
98     ASUS           Intel        Core i3            10th   4 GB     DDR4
99      MSI           Intel        Core i3            11th   8 GB     DDR4
100      HP           Intel        Core i3            11th   8 GB     DDR4
101     MSI           Intel        Core i3            10th   8 GB     DDR4
102    ASUS           Intel        Core i3            11th   8 GB     DDR4
103  Lenovo           Intel        Core i3            11th   8 GB     DDR4
104    ASUS           Intel        Core i3            11th   8 GB     DDR4
105      HP           Intel        Core i3            11th   8 GB     DDR4
106      HP           Intel        Core i3            11th   8 GB     DDR4
107    ASUS           Intel        Core i3            11th   8 GB     DDR4
108    DELL           Intel        Core i3            11th   8 GB     DDR4
109      HP           Intel        Core i3            11th   8 GB     DDR4
110    DELL           Intel        Core i3            10th   8 GB     DDR4
111    DELL           Intel        Core i3            10th   8 GB     DDR4
112    ASUS           Intel        Core i3            11th   8 GB     DDR4
113  Lenovo           Intel        Core i3            11th   8 GB     DDR4
114      HP           Intel        Core i3            11th   4 GB     DDR4
115      HP           Intel        Core i3            10th   4 GB     DDR4
116      HP           Intel        Core i3            11th   4 GB     DDR4
117    ASUS           Intel        Core i3            11th   4 GB     DDR4
118      HP           Intel        Core i3            11th   4 GB     DDR4
119    ASUS           Intel        Core i3            10th   4 GB     DDR4
120    ASUS           Intel        Core i3            10th   4 GB     DDR4
121    ASUS           Intel        Core i3            11th   4 GB     DDR4
122    ASUS           Intel        Core i3            10th   4 GB     DDR4
123      HP           Intel        Core i3            11th   4 GB     DDR4
124      HP           Intel        Core i3            11th   4 GB     DDR4
125    ASUS           Intel        Core i3            10th   4 GB     DDR4
126    DELL           Intel        Core i3            10th   4 GB     DDR4
127  Lenovo           Intel        Core i3            11th   4 GB     DDR4
128    DELL           Intel        Core i3            11th   8 GB     DDR4
129      HP           Intel        Core i3            11th   8 GB     DDR4
130    ASUS           Intel        Core i3            10th   8 GB     DDR4
131  Lenovo           Intel        Core i3            10th   8 GB     DDR4
132    DELL           Intel        Core i3            11th   8 GB     DDR4
133    DELL           Intel        Core i3            11th   8 GB     DDR4
134    DELL           Intel        Core i3            10th   8 GB     DDR4
135      HP           Intel        Core i3            11th   8 GB     DDR4
136    ASUS           Intel        Core i3            10th   4 GB     DDR4
137    DELL           Intel        Core i3            11th   8 GB     DDR4
138  Lenovo           Intel        Core i3            10th   8 GB     DDR4
139    ASUS           Intel        Core i3            10th   4 GB     DDR4
140    ASUS           Intel        Core i3            11th   8 GB     DDR4
141    DELL           Intel        Core i3            10th   4 GB     DDR4
142    DELL           Intel        Core i3            10th   4 GB     DDR4
143  Lenovo           Intel        Core i3            10th   4 GB     DDR4
144      HP           Intel        Core i3            11th   4 GB     DDR4
145      HP           Intel        Core i3            11th   4 GB     DDR4
146    DELL           Intel        Core i3            11th   4 GB     DDR4
147      HP           Intel        Core i3            11th   4 GB     DDR4
148    ASUS           Intel        Core i3            10th   4 GB     DDR4
149      HP           Intel        Core i3            10th   4 GB     DDR4
150    ASUS           Intel        Core i3            10th   4 GB     DDR4
151    ASUS           Intel        Core i3            10th   4 GB     DDR4
152    DELL           Intel        Core i3            10th   4 GB     DDR4
153    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
154      HP           Intel        Core i3            10th   4 GB     DDR4
155    DELL           Intel        Core i3            10th   4 GB     DDR4
156    ASUS           Intel        Core i3            10th   4 GB     DDR4
157    DELL           Intel        Core i3            11th   8 GB     DDR4
158      HP           Intel        Core i3             7th   8 GB     DDR4
159  Lenovo           Intel        Core i3            10th   8 GB     DDR4
160    ASUS           Intel        Core i3            11th   8 GB     DDR4
161    acer           Intel        Core i3            11th   4 GB     DDR4
162    DELL           Intel        Core i3            11th   8 GB     DDR4
163    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
164    DELL           Intel        Core i3            11th   8 GB     DDR4
165    ASUS           Intel        Core i3            10th   8 GB     DDR4
166    ASUS           Intel        Core i3            11th   8 GB     DDR4
167    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
168    DELL           Intel        Core i3            10th   8 GB     DDR4
169    ASUS           Intel        Core i3            10th   4 GB     DDR4
170    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
171    DELL           Intel        Core i3            10th   8 GB     DDR4
172    DELL           Intel        Core i3            11th   8 GB     DDR4
173    DELL           Intel        Core i3            11th   8 GB     DDR4
174    ASUS           Intel        Core i3            11th   8 GB     DDR4
175    DELL           Intel        Core i3            11th   4 GB     DDR4
176    acer           Intel        Core i3            11th   8 GB     DDR4
177    DELL           Intel        Core i3            11th   8 GB     DDR4
178    DELL           Intel        Core i3            11th   4 GB     DDR4
179    DELL           Intel        Core i3            10th   4 GB     DDR4
180    ASUS           Intel        Core i3            10th   4 GB     DDR4
181    DELL           Intel        Core i3            11th   4 GB     DDR4
182    DELL           Intel        Core i3            11th   4 GB     DDR4
183    DELL           Intel        Core i3            10th   4 GB     DDR4
184    DELL           Intel        Core i3            10th   4 GB     DDR4
185    DELL           Intel        Core i3            11th   4 GB     DDR4
186    DELL           Intel        Core i3            11th   4 GB     DDR4
187    DELL           Intel        Core i3            10th   8 GB     DDR4
188    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
189    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
190      HP           Intel   Celeron Dual   Not Available   4 GB     DDR4
191      HP           Intel   Celeron Dual   Not Available   4 GB     DDR4
192  Lenovo           Intel   Celeron Dual   Not Available   4 GB     DDR4
193  Lenovo           Intel   Celeron Dual   Not Available   4 GB  LPDDR4X
194  Lenovo           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
195  Lenovo           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
196    acer           Intel        Core i5   Not Available   8 GB     DDR5
197    acer           Intel        Core i5   Not Available   8 GB   LPDDR4
198    acer           Intel        Core i5            10th   8 GB   LPDDR4
199    ASUS           Intel        Core i5            10th   8 GB   LPDDR4
200    DELL           Intel        Core i5            10th   8 GB   LPDDR4
201    DELL           Intel        Core i5            10th   8 GB   LPDDR4
202      HP           Intel        Core i5            10th   8 GB   LPDDR4
203      HP           Intel        Core i5            10th   8 GB   LPDDR4
204  Lenovo           Intel        Core i5            10th   8 GB   LPDDR4
205      HP           Intel        Core i5             8th   8 GB     DDR4
206  Lenovo           Intel        Core i5            11th   8 GB     DDR4
207    acer           Intel        Core i5             7th   8 GB     DDR3
208    ASUS           Intel        Core i5            11th   8 GB     DDR4
209    DELL           Intel        Core i5            11th   8 GB     DDR4
210    acer           Intel        Core i5             8th   8 GB     DDR3
211      HP           Intel        Core i5             8th   8 GB     DDR4
212    acer           Intel        Core i5             8th   8 GB     DDR4
213    ASUS           Intel        Core i5            11th   8 GB     DDR4
214  Lenovo           Intel        Core i5            11th   8 GB     DDR4
215      HP           Intel        Core i5            11th   8 GB     DDR4
216      HP           Intel        Core i5            11th   8 GB     DDR4
217  Lenovo           Intel        Core i5            11th   8 GB     DDR4
218      HP           Intel        Core i5            11th  16 GB     DDR4
219    ASUS           Intel        Core i5            10th   8 GB     DDR4
220  Lenovo           Intel        Core i5            11th  16 GB     DDR4
221  Lenovo           Intel        Core i5            11th   8 GB     DDR4
222  Lenovo           Intel        Core i5            11th   8 GB     DDR4
223  Lenovo           Intel        Core i5            11th  16 GB     DDR4
224    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
225  Lenovo           Intel        Core i5            11th   8 GB     DDR4
226    acer           Intel        Core i5            11th   8 GB     DDR4
227  Lenovo           Intel        Core i5            10th   8 GB     DDR4
228    ASUS           Intel        Core i5            11th   8 GB     DDR4
229    ASUS           Intel        Core i5            10th   8 GB     DDR4
230  Lenovo           Intel        Core i5            10th   8 GB     DDR4
231    ASUS           Intel        Core i5            11th   8 GB     DDR4
232     MSI           Intel        Core i5            11th  16 GB     DDR4
233    ASUS           Intel        Core i5            11th  16 GB     DDR4
234     MSI           Intel        Core i5            10th   8 GB     DDR4
235    ASUS           Intel        Core i5            10th   8 GB     DDR4
236    DELL           Intel        Core i5            11th   8 GB     DDR4
237    DELL           Intel        Core i5            11th   8 GB     DDR4
238  Lenovo           Intel        Core i5            11th  16 GB     DDR4
239    ASUS           Intel        Core i5            11th  16 GB     DDR4
240      HP           Intel        Core i5            11th   8 GB     DDR4
241    ASUS           Intel        Core i5            11th  16 GB     DDR4
242      HP           Intel        Core i5            11th  16 GB     DDR4
243      HP           Intel        Core i5            11th   8 GB     DDR4
244    acer           Intel        Core i5            11th   8 GB     DDR4
245    DELL           Intel        Core i5            11th  16 GB     DDR4
246    ASUS           Intel        Core i5            11th  16 GB     DDR4
247    ASUS           Intel        Core i5            11th  16 GB     DDR4
248    DELL           Intel        Core i5            11th   8 GB     DDR4
249    DELL           Intel        Core i5            11th  16 GB     DDR4
250    ASUS           Intel        Core i5            10th   8 GB     DDR4
251     MSI           Intel        Core i5            11th   8 GB     DDR4
252      HP           Intel        Core i5            11th   8 GB  LPDDR4X
253    ASUS           Intel        Core i5             9th   8 GB     DDR4
254  Lenovo           Intel        Core i5            11th   8 GB     DDR4
255  Lenovo           Intel        Core i5            11th   8 GB     DDR4
256      HP           Intel        Core i5            11th  16 GB     DDR4
257    acer           Intel        Core i5            11th   8 GB  LPDDR4X
258    ASUS           Intel        Core i5            10th   8 GB     DDR4
259      HP           Intel        Core i5            11th   8 GB     DDR4
260    DELL           Intel        Core i5            10th  16 GB     DDR4
261    ASUS           Intel        Core i5            10th   8 GB     DDR4
262      HP           Intel        Core i5            11th   8 GB     DDR4
263    ASUS           Intel        Core i5            11th  16 GB     DDR4
264  Lenovo           Intel        Core i5            11th   8 GB     DDR4

In [90]:
# Para que el orden se aplique al dataframe original
datos.sort_values(by=["brand", "rating","Price"], inplace=True)

In [91]:
datos  #ahora si ya el DataFrame está ordenado

      brand processor_brand processor_name processor_gnrtn ram_gb ram_type  \
599   APPLE              M1             M1            10th   8 GB     DDR4
605   APPLE              M1             M1            10th   8 GB     DDR4
609   APPLE              M1             M1            10th   8 GB     DDR4
608   APPLE              M1             M1            10th   8 GB     DDR4
601   APPLE              M1             M1            10th  16 GB     DDR4
604   APPLE              M1             M1            10th  16 GB     DDR4
610   APPLE              M1             M1            10th   8 GB     DDR4
616   APPLE              M1             M1            10th   8 GB     DDR4
600   APPLE              M1             M1            10th   8 GB     DDR4
602   APPLE              M1             M1            10th   8 GB     DDR4
615   APPLE              M1             M1            10th   4 GB     DDR4
607   APPLE              M1             M1            10th   8 GB     DDR4
612   APPLE              M1             M1            10th  16 GB     DDR4
611   APPLE              M1             M1            10th   8 GB     DDR4
603   APPLE              M1             M1            10th  16 GB     DDR4
606   APPLE              M1             M1            10th  16 GB     DDR4
617   APPLE              M1             M1            10th   8 GB     DDR4
309   APPLE           Intel        Core i5            10th   8 GB  LPDDR4X
618   APPLE              M1             M1            10th  16 GB     DDR4
310   APPLE           Intel        Core i5             8th   8 GB     DDR3
407   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
408   APPLE           Intel        Core i5            10th  16 GB  LPDDR4X
613   APPLE              M1             M1            10th  16 GB     DDR4
614   APPLE              M1             M1            10th  16 GB     DDR4
619   APPLE              M1             M1            10th  16 GB     DDR4
622   APPLE              M1             M1            10th  16 GB     DDR4
620   APPLE              M1             M1            10th  16 GB     DDR4
621   APPLE              M1             M1            10th  32 GB     DDR4
165    ASUS           Intel        Core i3            10th   8 GB     DDR4
0      ASUS           Intel        Core i3            10th   4 GB     DDR4
723    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
189    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
188    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
170    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
163    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
6      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
5      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
13     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
21     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
633    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
634    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
4      ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
632    ASUS           Intel   Pentium Quad   Not Available   4 GB   LPDDR4
635    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
130    ASUS           Intel        Core i3            10th   8 GB     DDR4
151    ASUS           Intel        Core i3            10th   4 GB     DDR4
169    ASUS           Intel        Core i3            10th   4 GB     DDR4
139    ASUS           Intel        Core i3            10th   4 GB     DDR4
148    ASUS           Intel        Core i3            10th   4 GB     DDR4
14     ASUS           Intel        Core i3            11th   4 GB     DDR4
60     ASUS           Intel        Core i3            10th   4 GB     DDR4
136    ASUS           Intel        Core i3            10th   4 GB     DDR4
52     ASUS           Intel        Core i3            11th   8 GB     DDR4
166    ASUS           Intel        Core i3            11th   8 GB     DDR4
140    ASUS           Intel        Core i3            11th   8 GB     DDR4
70     ASUS           Intel        Core i3            10th   4 GB     DDR4
180    ASUS           Intel        Core i3            10th   4 GB     DDR4
160    ASUS           Intel        Core i3            11th   8 GB     DDR4
68     ASUS           Intel        Core i3            11th   4 GB     DDR4
102    ASUS           Intel        Core i3            11th   8 GB     DDR4
121    ASUS           Intel        Core i3            11th   4 GB     DDR4
112    ASUS           Intel        Core i3            11th   8 GB     DDR4
623    ASUS           Intel   Pentium Quad   Not Available   4 GB  LPDDR4X
74     ASUS           Intel        Core i3            11th   4 GB     DDR4
83     ASUS           Intel        Core i3            11th   8 GB     DDR4
208    ASUS           Intel        Core i5            11th   8 GB     DDR4
213    ASUS           Intel        Core i5            11th   8 GB     DDR4
462    ASUS           Intel        Core i5            11th   8 GB     DDR4
117    ASUS           Intel        Core i3            11th   4 GB     DDR4
445    ASUS           Intel        Core i5            11th   8 GB     DDR4
427    ASUS           Intel        Core i5            10th   8 GB     DDR4
751    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
329    ASUS           Intel        Core i5            11th   8 GB     DDR4
624    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
7      ASUS           Intel        Core i5            10th   8 GB     DDR4
274    ASUS           Intel        Core i5            11th  16 GB     DDR4
263    ASUS           Intel        Core i5            11th  16 GB     DDR4
265    ASUS           Intel        Core i5            11th  16 GB     DDR4
278    ASUS           Intel        Core i5            11th  16 GB     DDR4
430    ASUS           Intel        Core i5            10th   8 GB     DDR4
625    ASUS           Intel   Pentium Quad   Not Available   8 GB  LPDDR4X
261    ASUS           Intel        Core i5            10th   8 GB     DDR4
466    ASUS           Intel        Core i5            11th   8 GB     DDR4
239    ASUS           Intel        Core i5            11th  16 GB     DDR4
3      ASUS           Intel        Core i5            10th   8 GB     DDR4
759    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
269    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
739    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
392    ASUS           Intel        Core i5            11th   8 GB     DDR4
783    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
741    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
745    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
768    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
718    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
429    ASUS           Intel        Core i5             8th   8 GB     DDR4
581    ASUS           Intel        Core i7            11th  16 GB     DDR4
432    ASUS           Intel        Core i5            10th   8 GB     DDR4
791    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
349    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
352    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
359    ASUS           Intel        Core i5            11th   8 GB   LPDDR4
382    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
395    ASUS           Intel        Core i5            11th   8 GB     DDR4
379    ASUS           Intel        Core i5             8th   8 GB     DDR4
380    ASUS           Intel        Core i5            10th   8 GB     DDR4
410    ASUS           Intel        Core i5            11th   8 GB     DDR4
362    ASUS           Intel        Core i5            11th   8 GB     DDR4
705    ASUS             AMD        Ryzen 5   Not Available   4 GB  LPDDR4X
577    ASUS           Intel        Core i7            10th  16 GB     DDR4
494    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
524    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
584    ASUS           Intel        Core i7             8th  16 GB     DDR4
351    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
375    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
538    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
785    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
534    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
748    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
521    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
790    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
762    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
778    ASUS             AMD        Ryzen 7   Not Available  16 GB  LPDDR4X
786    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
368    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
779    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR5
815    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
561    ASUS           Intel        Core i7            11th  16 GB     DDR4
810    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
808    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
814    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
564    ASUS           Intel        Core i7            11th  16 GB     DDR4
386    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
535    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
806    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
796    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
818    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
816    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
592    ASUS           Intel        Core i9            11th  16 GB     DDR4
821    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
819    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
598    ASUS           Intel        Core i7            10th  16 GB  LPDDR4X
820    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
813    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
566    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
568    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
540    ASUS           Intel        Core i7            11th  16 GB     DDR4
576    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
557    ASUS           Intel        Core i7            10th  16 GB     DDR4
817    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
590    ASUS           Intel        Core i9            12th  16 GB     DDR5
84     ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
167    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
153    ASUS           Intel   Celeron Dual   Not Available   4 GB   LPDDR4
20     ASUS           Intel   Celeron Dual   Not Available   4 GB     DDR4
630    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
641    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
27     ASUS           Intel        Core i3            10th   8 GB     DDR4
627    ASUS           Intel   Pentium Quad   Not Available   4 GB     DDR4
24     ASUS           Intel        Core i3            11th   4 GB     DDR4
644    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
26     ASUS           Intel        Core i3            11th   4 GB     DDR4
89     ASUS           Intel        Core i3            10th   4 GB     DDR4
637    ASUS             AMD        Ryzen 3   Not Available   8 GB     DDR4
42     ASUS           Intel        Core i3            11th   8 GB     DDR4
81     ASUS           Intel        Core i3            11th   4 GB     DDR4
33     ASUS           Intel        Core i3            11th   8 GB     DDR4
32     ASUS           Intel        Core i3            11th   8 GB     DDR4
86     ASUS           Intel        Core i3            10th   8 GB     DDR4
643    ASUS             AMD        Ryzen 3   Not Available   4 GB     DDR4
156    ASUS           Intel        Core i3            10th   4 GB     DDR4
150    ASUS           Intel        Core i3            10th   4 GB     DDR4
66     ASUS           Intel        Core i3            11th   4 GB     DDR4
98     ASUS           Intel        Core i3            10th   4 GB     DDR4
119    ASUS           Intel        Core i3            10th   4 GB     DDR4
125    ASUS           Intel        Core i3            10th   4 GB     DDR4
122    ASUS           Intel        Core i3            10th   4 GB     DDR4
174    ASUS           Intel        Core i3            11th   8 GB     DDR4
90     ASUS           Intel        Core i3            11th   8 GB     DDR4
93     ASUS           Intel        Core i3            11th   8 GB     DDR4
107    ASUS           Intel        Core i3            11th   8 GB     DDR4
120    ASUS           Intel        Core i3            10th   4 GB     DDR4
104    ASUS           Intel        Core i3            11th   8 GB     DDR4
37     ASUS           Intel        Core i3            11th   8 GB     DDR4
45     ASUS           Intel        Core i3            11th   8 GB     DDR4
420    ASUS           Intel        Core i5            10th   8 GB     DDR4
229    ASUS           Intel        Core i5            10th   8 GB     DDR4
258    ASUS           Intel        Core i5            10th   8 GB     DDR4
92     ASUS           Intel        Core i3            11th   8 GB     DDR4
694    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
250    ASUS           Intel        Core i5            10th   8 GB     DDR4
716    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
442    ASUS           Intel        Core i5            11th   8 GB     DDR4
91     ASUS           Intel        Core i3            11th   8 GB  LPDDR4X
345    ASUS           Intel        Core i5            11th   8 GB     DDR4
305    ASUS           Intel        Core i5            11th   8 GB     DDR4
343    ASUS           Intel        Core i5             8th   8 GB     DDR4
453    ASUS           Intel        Core i5             9th   8 GB     DDR4
253    ASUS           Intel        Core i5             9th   8 GB     DDR4
730    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
732    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
733    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
443    ASUS           Intel        Core i5            10th   8 GB     DDR4
689    ASUS             AMD        Ryzen 5   Not Available  16 GB     DDR4
219    ASUS           Intel        Core i5            10th   8 GB     DDR4
485    ASUS           Intel        Core i7            10th  16 GB     DDR4
457    ASUS           Intel        Core i5            11th  16 GB     DDR4
687    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
701    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
246    ASUS           Intel        Core i5            11th  16 GB     DDR4
452    ASUS           Intel        Core i5            11th   8 GB     DDR4
486    ASUS           Intel        Core i7            10th   8 GB     DDR4
686    ASUS             AMD        Ryzen 5   Not Available   8 GB     DDR4
737    ASUS             AMD        Ryzen 5   Not Available   4 GB     DDR4
224    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
756    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
320    ASUS           Intel        Core i5            10th   8 GB     DDR4
450    ASUS           Intel        Core i5            11th  16 GB     DDR4
456    ASUS           Intel        Core i5            11th  16 GB     DDR4
235    ASUS           Intel        Core i5            10th   8 GB     DDR4
580    ASUS           Intel        Core i7            10th  16 GB     DDR4
228    ASUS           Intel        Core i5            11th   8 GB     DDR4
742    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
743    ASUS             AMD        Ryzen 7   Not Available   8 GB     DDR4
231    ASUS           Intel        Core i5            11th   8 GB     DDR4
299    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
327    ASUS           Intel        Core i5             8th   8 GB   LPDDR3
775    ASUS             AMD        Ryzen 7   Not Available   8 GB  LPDDR4X
241    ASUS           Intel        Core i5            11th  16 GB     DDR4
337    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
402    ASUS           Intel        Core i5            10th   8 GB     DDR4
404    ASUS           Intel        Core i5            11th   8 GB     DDR4
740    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
405    ASUS           Intel        Core i5            11th   8 GB     DDR4
406    ASUS           Intel        Core i5            10th   8 GB     DDR4
491    ASUS           Intel        Core i7            11th   8 GB     DDR4
508    ASUS           Intel        Core i7            11th  16 GB     DDR4
302    ASUS           Intel        Core i5            10th   8 GB   LPDDR3
531    ASUS           Intel        Core i7             8th   8 GB   LPDDR3
247    ASUS           Intel        Core i5            11th  16 GB     DDR4
409    ASUS           Intel        Core i5            10th   8 GB     DDR4
747    ASUS             AMD        Ryzen 7   Not Available  16 GB     DDR4
411    ASUS           Intel        Core i5            11th   8 GB     DDR4
295    ASUS           Intel        Core i5            11th   8 GB     DDR4
510    ASUS           Intel        Core i7             8th  16 GB   LPDDR3
233    ASUS           Intel        Core i5            11th  16 GB     DDR4
749    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
499    ASUS           Intel        Core i7            11th  16 GB     DDR4
781    ASUS             AMD        Ryzen 7   Not Available   4 GB     DDR4
536    ASUS           Intel        Core i7            11th  16 GB     DDR4
339    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
522    ASUS           Intel        Core i7             8th  16 GB     DDR3
789    ASUS             AMD        Ryzen 7   Not Available   4 GB  LPDDR4X
803    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
291    ASUS           Intel        Core i5            11th   8 GB  LPDDR4X
199    ASUS           Intel        Core i5            10th   8 GB   LPDDR4
799    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
801    ASUS             AMD        Ryzen 9   Not Available  16 GB  LPDDR4X
804    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
560    ASUS           Intel        Core i7            11th  16 GB  LPDDR4X
541    ASUS           Intel        Core i7            10th  16 GB   LPDDR3
811    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
800    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4
812    ASUS             AMD        Ryzen 9   Not Available   4 GB     DDR4
809    ASUS             AMD        Ryzen 9   Not Available   4 GB  LPDDR4X
797    ASUS             AMD        Ryzen 9   Not Available  16 GB     DDR4